<h4 style="text-align: center"></h4>

<?php $colspan = count($context->getConfig('commitment/accountList'.(($type) ? '/'.$type : ''))['properties'])
//	   		   + count($context->getConfig('commitment/accountList'.(($type) ? '/'.$type : ''))['glyphicons'])
	   		   + count($context->getConfig('commitment/accountList'.(($type) ? '/'.$type : ''))['anchors']) 
			   + 2 ?>

<table class="table table-striped ppit_index">
	<tr>
		<th colspan="<?php echo $colspan ?>" style="font-size: large; text-align: center">
			<strong><?php echo $context->getConfig('commitment/accountList'.(($type) ? '/'.$type : ''))['title'][$context->getLocale()] ?></strong>
		</th>
	</tr>
	<tr>
		<td colspan="<?php echo $colspan ?>">
<!--			<button type="button" class="btn btn-default action-btn btn-xs commitment-add-anchor" title="<?php echo $this->translate('Detail', 'ppit-core', $context->getLocale())?>" id="commitment-add">
				<span class="glyphicon glyphicon-plus" id="add-glyphicon"></span>
			</button> -->
<?php if ($context->isDemoModeActive()) : ?>
			<a class="tip" href="#" title="<?php echo $context->getConfig('demo')['commitment/accountList'.(($type) ? '/'.$type : '').'/add'][$context->getLocale()] ?>">
			    <img src="<?php echo $this->basePath('img/tip.png') ?>" width="20" />
			</a>
<?php endif;?>
			<button type="button" class="btn btn-default action-btn btn-xs account-list-anchor" title="<?php echo $this->translate('Detail', 'ppit-core', $context->getLocale())?>" id="<?php echo $this->url('commitment/index', array('type' => $type)) ?>?account_id=<?php echo $params['account_id'] ?>">
				<?php echo $this->translate('Invoices', 'ppit-commitment', $context->getLocale()) ?>
			</button>
		</td>
	</tr>

<?php $i = 0; foreach ($commitments as $commitment) : ?>

	<tr class="commitment">
		
	<?php foreach ($context->getConfig('commitment/accountList'.(($type) ? '/'.$type : ''))['properties'] as $propertyId => $rendering) : ?>
		<?php if ($propertyId == 'caption') : ?>
		<td style="text-align: center"><strong><?php echo $commitment->caption ?></strong></td>

		<?php else : ?>
		<td style="text-align: center"><strong><?php echo $commitment->properties[$propertyId] ?></strong></td>

		<?php endif;?>
		
	<?php endforeach;?>
		<td>
			<button type="button" class="btn btn-default action-btn btn-xs commitment-detail-anchor" title="<?php echo $this->translate('Detail', 'ppit-core', $context->getLocale())?>" id="commitment-detail_<?php echo $commitment->id ?>">
				<span class="glyphicon glyphicon-edit" id="<?php echo $commitment->id ?>-zoom-glyphicon"></span>
			</button>
		</td>
		<td>
			<button type="button" class="btn btn-default action-btn btn-xs commitment-delete-anchor" title="<?php echo $this->translate('Detail', 'ppit-core', $context->getLocale())?>" id="commitment-delete_<?php echo $commitment->id ?>">
				<span class="glyphicon glyphicon-trash" id="<?php echo $commitment->id ?>-delete-glyphicon"></span>
			</button>
		</td>

	<?php foreach ($context->getConfig('commitment/accountList'.(($type) ? '/'.$type : ''))['anchors'] as $route => $params) : ?>
		<td>
		<?php if ($params['type'] == 'btn') : ?>
			<button type="button" class="btn btn-default action-btn btn-xs account-list-anchor" id="<?php echo $this->url($route, array('id' => $commitment->id)) ?>" <?php if (!$context->isAllowed($route)) echo 'disabled="disabled"' ?>>
				<?php echo $params['labels'][$context->getLocale()] ?> Old
			</button>
		<?php elseif ($params['type'] == 'nav') : ?>
			<ul class="nav nav-tabs">
		        <li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"><?php echo $params['labels'][$context->getLocale()] ?> <span class="caret"></span></a>
		          <ul class="dropdown-menu">
			<?php foreach ($params['entries'] as $childRoute => $childParams) : ?>
				 <?php if ($context->isAllowed($childRoute)) : ?>
		          	<li class="dropdown-item"><a class="account-list-anchor" id="<?php echo $this->url($childRoute, array('id' => $commitment->id)) ?>" href="#"><?php echo $childParams['labels'][$context->getLocale()] ?></a></li>
		         <?php endif;?>
		    <?php endforeach;?>
		          </ul>
		        </li>
<?php if ($i == 0 && $context->isDemoModeActive()) : ?>
			<a class="tip" href="#" title="<?php echo $context->getConfig('demo')['commitment/accountList'.(($type) ? '/'.$type : '').'/documents'][$context->getLocale()] ?>">
			    <img src="<?php echo $this->basePath('img/tip.png') ?>" width="20" />
			</a>
<?php endif;?>
		    </ul>
		<?php endif;?>
		</td>
	<?php endforeach;?>	
	</tr>

<?php $i++; endforeach; ?>

</table>

<div id="commitment-update-panel"></div>
