<div class="panel panel-default">
	<div class="panel-heading" style="background: <?php echo $context->getConfig('styleSheet')['panelHeadingBackground'] ?>; color: <?php echo $context->getConfig('styleSheet')['panelHeadingColor'] ?>">
		<strong><?php echo $this->translate('Detail', 'ppit-core', $context->getLocale()) ?></strong>
 		<div class="btn-group pull-right">
			<button type="button" class="btn btn-default" title="<?php echo $this->translate('Return to list', 'ppit-core', $context->getLocale()) ?>" id="remove-anchor">
				<span class="glyphicon glyphicon-remove"></span>
			</button>
 		 </div>
	</div>
	<div class="panel-body">

<!-- Display the audit -->
		<?php echo $this->translate('History', 'ppit-core', $context->getLocale()) ?> (<a id="audit-label" href="#audit-panel"><?php echo $this->translate('Show', 'ppit-core', $context->getLocale()) ?></a>)
		<div id="audit-panel" class="panel panel-default">
			<div class="panel-body">
<?php foreach ($commitment->audit as $comment) : ?>
				<div class="row">
					<div class="col-md-12">
						<strong><?php echo $context->decodeDate(substr($comment['time'], 0, 10)).substr($comment['time'], 10) ?>:</strong>&nbsp;
						<?php echo $context->getConfig('commitment'.(($type) ? '/'.$type : ''))['statuses'][$comment['status']]['labels'][$context->getLocale()] ?>&nbsp;
						(<?php echo $comment['n_fn'] ?>)
					</div>
				</div>
				<div class="row">
					<div class="col-md-2" align="right">&nbsp;</div>
					<div class="col-md-10"><em><?php echo $comment['comment'] ?></em></div>
				</div>
<?php endforeach;?>
			</div>
		</div>

<?php if ($commitment->cgv) : ?>
<!-- Display the CGV -->
		&nbsp;&nbsp;<?php echo $this->translate('Terms and Conditions', 'ppit-commitment', $context->getLocale()) ?> (<a id="cgv-label" href="#cgv-panel"><?php echo $this->translate('Show', 'ppit-core', $context->getLocale()) ?></a>)
		<div id="cgv-panel" class="panel panel-default">
			<div class="panel-body">
				<?php echo $commitment->cgv ?>
			</div>
		</div>
<?php endif;?>
		<div>&nbsp;</div>

<?php if ($commitment->id) : ?>
	<?php foreach ($context->getConfig('commitment'.(($type) ? '/'.$type : ''))['actions'] as $actionId => $action) : ?>
			<?php if (array_key_exists($commitment->status, $action['currentStatuses'])) : ?>
			<button type="button" class="btn btn-default action-btn" id="<?php echo $actionId ?>-anchor" title="<?php echo $action['label'][$context->getLocale()]?>">
			<?php if (array_key_exists('glyphicon', $action)) : ?>
				<span class="glyphicon <?php echo $action['glyphicon'] ?>"></span>
			<?php else : ?>
				<span><?php echo $action['label'][$context->getLocale()]?></span>
			<?php endif;?>
			</button>
			<?php endif;?>
	<?php endforeach;?>
<?php endif;?>

	<div id="commitment-update-panel"></div>

	<div id="commitment-options-panel">
		<h4><?php echo $this->translate('Options', 'ppit-commitment', $context->getLocale()) ?></h4>
		<table class="table table-striped ppit_index">
			<tr>
				<th>&nbsp;</th>
				<th>&nbsp;</th>
				<th><?php echo $this->translate('Caption', 'ppit-core', $context->getLocale()) ?></th>
				<th><?php echo $this->translate('Quantity', 'ppit-core', $context->getLocale()) ?></th>
				<th><?php echo $this->translate('Unit price', 'ppit-commitment', $context->getLocale()) ?></th>
				<th><?php echo $this->translate('Amount', 'ppit-commitment', $context->getLocale()) ?></th>
				<th><?php echo $this->translate('VAT', 'ppit-commitment', $context->getLocale()) ?></th>
			</tr>
		
<?php foreach ($commitment->options as $option) : ?>
			<tr class="option">
				<td>
					<button type="button" class="btn btn-default action-btn btn-xs option-list-anchor" title="<?php echo $params['labels'][$context->getLocale()] ?>" id="option-list-anchor_<?php $commitment->id ?>">
						<span class="glyphicon glyphicon-edit" id="<?php echo $commitment->id ?>-glyphicon"></span>
					</button>
				</td>
				<td>
					<button type="button" class="btn btn-default action-btn btn-xs option-list-anchor" title="<?php echo $params['labels'][$context->getLocale()] ?>" id="option-list-anchor_<?php $commitment->id ?>">
						<span class="glyphicon glyphicon-trash" id="<?php echo $commitment->id ?>-glyphicon"></span>
					</button>
				</td>
				<td style="text-align: left"><?php echo $option['caption'] ?></td>
				<td style="text-align: right"><?php echo $option['quantity'] ?></td>
				<td style="text-align: right"><?php echo $context->formatFloat($option['unit_price'], 2) ?></td>
				<td style="text-align: right"><?php echo $context->formatFloat($option['amount'], 2) ?></td>
				<td style="text-align: right"><?php echo $context->formatFloat($option['vat_rate']*100, 2) ?></td>
			</tr>
			<tr class="option">
				<td>
					<button type="button" class="btn btn-warning action-btn btn-xs option-list-anchor" title="<?php echo $params['labels'][$context->getLocale()] ?>" id="option-list-anchor_<?php $commitment->id ?>">
						<span class="glyphicon glyphicon-edit" id="<?php echo $commitment->id ?>-glyphicon"></span>
					</button>
				</td>
				<td>&nbsp;</td>
				<td style="text-align: left">
					<input class="form-control" id="option_caption-<?php echo $commitment->id ?>" value="<?php echo $option['caption'] ?>" />
				</td>
				<td style="text-align: right">
					<input class="form-control" id="option_quantity-<?php echo $commitment->id ?>" value="<?php echo $option['quantity'] ?>" />
				</td>
				<td style="text-align: right">
					<input class="form-control" id="option_unit_price-<?php echo $commitment->id ?>" value="<?php echo $option['unit_price'] ?>" />
				</td>
				<td style="text-align: right">&nbsp;</td>
				<td style="text-align: right">
					<select class="form-control" id="option_vat_rate-<?php echo $commitment->id ?>">
						<option value="0.2" <?php if ($option['vat_rate'] == 0.2) echo 'selected="selected"' ?>>20%</option>
						<option value="0" <?php if ($option['vat_rate'] == 0) echo 'selected="selected"' ?>>Exonéré</option>
						<option value="0.055" <?php if ($option['vat_rate'] == 0.055) echo 'selected="selected"' ?>>5,5%</option>
					</select>
				</td>
			</tr>
<?php endforeach; ?>

			<tr>
				<td colspan="5">
					<button type="button" class="btn btn-default action-btn btn-xs option-list-anchor" title="<?php echo $this->translate('Add', 'ppit-core', $context->getLocale())?>" id="option-list-anchor">
						<span class="glyphicon glyphicon-plus" id="add-glyphicon"></span>
					</button>
				</td>
			</tr>
			<tr class="option">
				<td>
					<button type="button" class="btn btn-warning action-btn btn-xs option-list-anchor" title="<?php echo $params['labels'][$context->getLocale()] ?>" id="option-list-anchor_<?php $commitment->id ?>">
						<span class="glyphicon glyphicon-plus" id="<?php echo $commitment->id ?>-glyphicon"></span>
					</button>
				</td>
				<td>&nbsp;</td>
				<td style="text-align: left">
					<input class="form-control" id="option_caption" value="" />
				</td>
				<td style="text-align: right">
					<input class="form-control" id="option_quantity" value="" />
				</td>
				<td style="text-align: right">
					<input class="form-control" id="option_unit_price" value="" />
				</td>
				<td style="text-align: right">&nbsp;</td>
				<td style="text-align: right">
					<select class="form-control" id="option_vat_rate-<?php echo $commitment->id ?>">
						<option value="0.2" <?php if ($option['vat_rate'] == 0.2) echo 'selected="selected"' ?>>20%</option>
						<option value="0" <?php if ($option['vat_rate'] == 0) echo 'selected="selected"' ?>>Exonéré</option>
						<option value="0.055" <?php if ($option['vat_rate'] == 0.055) echo 'selected="selected"' ?>>5,5%</option>
					</select>
				</td>
			</tr>

		</table>
	</div>

	<div id="commitment-settlement-panel">
		<h4><?php echo $this->translate('Schedule', 'ppit-commitment', $context->getLocale()) ?></h4>
		<table class="table table-striped ppit_index">
			<tr>
				<th>&nbsp;</th>
				<th>&nbsp;</th>
				<th><?php echo $this->translate('Caption', 'ppit-core', $context->getLocale()) ?></th>
				<th><?php echo $this->translate('Date', 'ppit-core', $context->getLocale()) ?></th>
				<th><?php echo $this->translate('Amount', 'ppit-commitment', $context->getLocale()) ?></th>
				<th><?php echo $this->translate('Means', 'ppit-commitment', $context->getLocale()) ?></th>
				<th><?php echo $this->translate('Status', 'ppit-core', $context->getLocale()) ?></th>
			</tr>
		
<?php foreach ($commitment->terms as $term) : ?>
			<tr class="term">
				<td>
					<button type="button" class="btn btn-default action-btn btn-xs term-list-anchor" title="<?php echo $params['labels'][$context->getLocale()] ?>" id="term-list-update_<?php $commitment->id ?>">
						<span class="glyphicon glyphicon-edit" id="<?php echo $commitment->id ?>-glyphicon"></span>
					</button>
				</td>
				<td>
					<button type="button" class="btn btn-default action-btn btn-xs term-list-anchor" title="<?php echo $params['labels'][$context->getLocale()] ?>" id="term-list-delete_<?php $commitment->id ?>">
						<span class="glyphicon glyphicon-trash" id="<?php echo $commitment->id ?>-glyphicon"></span>
					</button>
				</td>
				<td style="text-align: left"><?php echo $term->caption ?></td>
				<td style="text-align: right"><?php echo $context->decodeDate($term->due_date) ?></td>
				<td style="text-align: right"><?php echo $context->formatFloat($term->amount, 2) ?></td>
				<td style="text-align: right"><?php echo $term->means_of_payment ?></td>
				<td style="text-align: right"><?php echo $term->status ?></td>
			</tr>
			<tr class="option">
				<td>
					<button type="button" class="btn btn-warning action-btn btn-xs term-list-anchor" title="<?php echo $params['labels'][$context->getLocale()] ?>" id="term-list-anchor_<?php $commitment->id ?>">
						<span class="glyphicon glyphicon-edit" id="<?php echo $commitment->id ?>-glyphicon"></span>
					</button>
				</td>
				<td>&nbsp;</td>
				<td style="text-align: left">
					<input class="form-control" id="term_caption-<?php echo $commitment->id ?>" value="<?php echo $term->caption ?>" />
				</td>
				<td style="text-align: right">
					<input class="form-control" id="term_due_date-<?php echo $commitment->id ?>" value="<?php echo $term->due_date ?>" />
				</td>
				<td style="text-align: right">
					<input class="form-control" id="term_amount-<?php echo $commitment->id ?>" value="<?php echo $term->amount ?>" />
				</td>
				<td style="text-align: right">&nbsp;</td>
				<td style="text-align: right">
					<select class="form-control" id="term_means_of_payment-<?php echo $commitment->id ?>">
						<option value="bank_card" <?php if ($option['vat_rate'] == 'bank_card') echo 'selected="selected"' ?>>CB</option>
						<option value="transfer" <?php if ($option['vat_rate'] == 'transfer') echo 'selected="selected"' ?>>Virement</option>
						<option value="check" <?php if ($option['vat_rate'] == 'check') echo 'selected="selected"' ?>>Chèque</option>
						<option value="cash" <?php if ($option['vat_rate'] == 'cash') echo 'selected="selected"' ?>>Espèces</option>
					</select>
				</td>
			</tr>
<?php endforeach; ?>

			<tr>
				<td colspan="5">
					<button type="button" class="btn btn-default action-btn btn-xs term-list-anchor" title="<?php echo $this->translate('Add', 'ppit-core', $context->getLocale())?>" id="term-list-anchor">
						<span class="glyphicon glyphicon-plus" id="add-glyphicon"></span>
					</button>
				</td>
			</tr>
			<tr class="option">
				<td>
					<button type="button" class="btn btn-warning action-btn btn-xs term-list-anchor" title="<?php echo $params['labels'][$context->getLocale()] ?>" id="term-list-anchor_<?php $commitment->id ?>">
						<span class="glyphicon glyphicon-plus" id="<?php echo $commitment->id ?>-glyphicon"></span>
					</button>
				</td>
				<td>&nbsp;</td>
				<td style="text-align: left">
					<input class="form-control" id="term_caption" value="" />
				</td>
				<td style="text-align: right">
					<input class="form-control" id="term_due_date" value="" />
				</td>
				<td style="text-align: right">
					<input class="form-control" id="term_amount" value="" />
				</td>
				<td style="text-align: right">&nbsp;</td>
				<td style="text-align: right">
					<select class="form-control" id="term_means_of_payment">
						<option value="bank_card" <?php if ($option['vat_rate'] == 'bank_card') echo 'selected="selected"' ?>>CB</option>
						<option value="transfer" <?php if ($option['vat_rate'] == 'transfer') echo 'selected="selected"' ?>>Virement</option>
						<option value="check" <?php if ($option['vat_rate'] == 'check') echo 'selected="selected"' ?>>Chèque</option>
						<option value="cash" <?php if ($option['vat_rate'] == 'cash') echo 'selected="selected"' ?>>Espèces</option>
					</select>
				</td>
			</tr>

		</table>
	</div>
