<table class="table table-striped ppit_index">
	<tr>
		<th>&nbsp;</th>

<?php foreach ($context->getConfig('commitment/list'.(($type) ? '/'.$type : '')) as $propertyId => $rendering) : ?>
		<th align="center">
	<?php $label = $context->getConfig('commitment'.(($type) ? '/'.$type : ''))['properties'][$propertyId]['labels'][$context->getLocale()] ?>
	<?php if ($label) : ?>
			<button type="button" class="btn btn-default btn-xs ppit-sort-anchor" id="<?php echo $propertyId ?>-anchor">
				<span><?php echo $label ?></span>
<?php if ($major == $propertyId) : ?>
				<span class="glyphicon glyphicon-triangle-<?php echo ($dir == 'ASC') ? 'top' : 'bottom' ?>"></span>
<?php endif ?>
			</button>
	<?php endif;?>
		</th>
<?php endforeach;?>
		
	<tr>
		<td>
			<button type="button" class="btn btn-default index-btn commitment-detail-anchor" title="<?php echo $this->translate('Add', 'ppit-core', $context->getLocale())?>" id="commitment-detail-anchor_0">
				<span class="glyphicon glyphicon-plus" id="add-glyphicon"></span>
			</button>
		</td>
		<td colspan="4">&nbsp;</td>
	</tr>
	
<?php foreach ($commitments as $commitment) : ?>
	<?php if ($context->isAllowed('commitment/detail')) : ?>
	
	<tr>
		<td colspan="6">
			<strong><?php echo $commitment->customer_name ?></strong> -
			<?php echo $commitment->caption ?>
		</td>
	</tr>
	
	<tr class="commitment">
		<td >
			<button type="button" class="btn btn-default index-btn commitment-detail-anchor" title="<?php echo $this->translate('Detail', 'ppit-core', $context->getLocale())?>" id="commitment-detail-anchor_<?php echo $commitment->id ?>">
				<span class="glyphicon glyphicon-zoom-in" id="<?php echo $commitment->id ?>-glyphicon"></span>
			</button>
		</td>

	<?php foreach ($context->getConfig('commitment/list'.(($type) ? '/'.$type : '')) as $propertyId => $rendering) : ?>
		<?php 
		$property = $context->getConfig('commitment'.(($type) ? '/'.$type : ''))['properties'][$propertyId];
		if ($property['type'] == 'repository') $property = $context->getConfig($property['definition']);
		?>
	
		<?php if ($propertyId == 'customer_name') : ?>
		<td><?php echo $commitment->customer_name ?></td>
	
		<?php elseif ($rendering == 'text') : ?>
		<td><?php echo $commitment->properties[$propertyId] ?></td>
	
		<?php elseif ($rendering == 'select') : ?>
		<td><?php echo ($commitment->properties[$propertyId]) ? $property['modalities'][$commitment->properties[$propertyId]][$context->getLocale()] : '' ?></td>
	
		<?php elseif ($rendering == 'number') : ?>
		<td style="text-align: right"><?php echo $context->formatFloat($commitment->properties[$propertyId], 2) ?></td>
	
		<?php else : ?>
		<td><?php echo $commitment->properties[$propertyId] ?></td>
		
		<?php endif;?>
		
	<?php endforeach;?>
	</tr>

	<?php endif;?>
<?php endforeach; ?>

</table>
