<table class="table table-striped ppit_index">

	<tr class="to-mask"><td colspan="<?php echo count($context->getConfig('commitment/list'.(($type) ? '/'.$type : ''))) + 1 ?>">&nbsp;</td></tr>	
	<tr style="font-weight: bold">
		<td colspan="<?php echo count($context->getConfig('commitment/list'.(($type) ? '/'.$type : ''))) + 1 ?>" style="text-align: right">
			<?php echo $this->translate(($type == 'learning' ? 'Interns' : 'Nbr'), 'ppit-commitment', $context->getLocale()) ?>:&nbsp;
			<?php echo count($commitments) ?>&nbsp;&nbsp;|&nbsp;&nbsp;
			<?php echo $this->translate(($type == 'learning' ? 'Hours' : 'Quantity'), 'ppit-commitment', $context->getLocale()) ?>:&nbsp;
			<?php echo $quantity ?>&nbsp;&nbsp;|&nbsp;&nbsp;
			<?php echo $this->translate('Sales', 'ppit-commitment', $context->getLocale()) ?>:&nbsp;
			<?php echo $context->formatFloat($turnover, 2) ?>
		</td>
	</tr>

	<tr>
		<th>&nbsp;</th>

<?php $first = true; foreach ($context->getConfig('commitment/list'.(($type) ? '/'.$type : '')) as $propertyId => $rendering) : ?>
		<th align="center">
	<?php $label = $context->getConfig('commitment'.(($type) ? '/'.$type : ''))['properties'][$propertyId]['labels'][$context->getLocale()] ?>
	<?php if ($label) : ?>
			<button type="button" class="btn btn-default btn-xs ppit-sort-anchor" id="<?php echo $propertyId ?>-anchor">
				<span><?php echo $label ?></span>
<?php if ($major == $propertyId) : ?>
				<span class="glyphicon glyphicon-triangle-<?php echo ($dir == 'ASC') ? 'top' : 'bottom' ?>"></span>
<?php endif ?>
			</button>
		<?php if ($first && $context->isDemoModeActive()) : ?>
			<a class="tip" href="#" title="<?php echo $context->getConfig('demo')['commitment/list/ordering'][$context->getLocale()] ?>">
			    <img src="<?php echo $this->basePath('img/tip.png') ?>" width="20" />
			</a>
		<?php $first=false; endif;?>
	<?php endif;?>
		</th>
<?php endforeach;?>
	
<?php $i = 0; foreach ($commitments as $commitment) : ?>
	<?php if ($context->isAllowed('commitment/detail')) : ?>
	
	<tr <?php if (in_array($commitment->credit_status, array('blocked', 'suspended', 'closed'))) echo 'style="font-style: italic"' ?>>
		<td colspan="<?php echo 1 + count($context->getConfig('commitment/list'.(($type) ? '/'.$type : '')))?>">
			<strong><?php echo $commitment->account_name ?></strong> -
			<?php echo $commitment->caption ?>
			<?php if ($commitment->credit_status == 'blocked') echo '('.$this->translate($commitment->credit_status, 'ppit-core', $context->getLocale()).')' ?>
		</td>
	</tr>
	
	<tr class="commitment" <?php if (in_array($commitment->credit_status, array('blocked', 'suspended', 'closed'))) echo 'style="font-style: italic"' ?>>
		<td >
			<button type="button" class="btn btn-default index-btn commitment-detail-anchor" title="<?php echo $this->translate('Detail', 'ppit-core', $context->getLocale())?>" id="commitment-detail-anchor_<?php echo $commitment->id ?>">
				<span class="glyphicon glyphicon-zoom-in" id="<?php echo $commitment->id ?>-glyphicon"></span>
			</button>
<?php if ($i == 0 && $context->isDemoModeActive()) : ?>
			<a class="tip" href="#" title="<?php echo $context->getConfig('demo')['commitment/list/detail'][$context->getLocale()] ?>">
			    <img src="<?php echo $this->basePath('img/tip.png') ?>" width="20" />
			</a>
<?php endif;?>
		</td>

	<?php foreach ($context->getConfig('commitment/list'.(($type) ? '/'.$type : '')) as $propertyId => $rendering) : ?>
		<?php 
		$property = $context->getConfig('commitment'.(($type) ? '/'.$type : ''))['properties'][$propertyId];
		if ($property['type'] == 'repository') $property = $context->getConfig($property['definition']);
		?>
	
		<?php if ($propertyId == 'account_name') : ?>
		<td><?php echo $commitment->account_name ?></td>
	
		<?php elseif ($rendering == 'text') : ?>
		<td><?php echo $commitment->properties[$propertyId] ?></td>
	
		<?php elseif ($rendering == 'select') : ?>
		<td><?php echo ($commitment->properties[$propertyId]) ? $property['modalities'][$commitment->properties[$propertyId]][$context->getLocale()] : '' ?></td>
	
		<?php elseif ($rendering == 'number') : ?>
		<td style="text-align: right"><?php echo $context->formatFloat($commitment->properties[$propertyId], 2) ?></td>
	
		<?php else : ?>
		<td><?php echo $commitment->properties[$propertyId] ?></td>
		
		<?php endif;?>
		
	<?php endforeach;?>
	</tr>

	<?php endif;?>
<?php $i++; endforeach; ?>

</table>
