<div class="panel panel-default">
	<div class="panel-heading" style="background: <?php echo $context->getConfig('styleSheet')['panelHeadingBackground'] ?>; color: <?php echo $context->getConfig('styleSheet')['panelHeadingColor'] ?>">
		<strong>
			<?php 
			$title = $this->translate('Commitments', 'ppit-commitment', $context->getLocale());
			echo $title;
			?>
			(<span id="mode-text"></span>)
		</strong>

<?php if ($context->isDemoModeActive()) : ?>
		<a class="tip" href="#" title="<?php echo $context->getConfig('demo')['commitment/search/title'][$context->getLocale()] ?>">
		    <img src="<?php echo $this->basePath('img/tip.png') ?>" width="20" />
		</a>
<?php endif;?>
	</div>
	<div class="panel-body">

		<div class="col-md-6">

<!-- Filters -->
		
<?php foreach ($searchPage['main'] as $propertyId => $rendering) : ?>
	<?php $property = $configProperties[$propertyId] ?>
	<?php $label = $property['labels'][$context->getLocale()] ?>

	<?php if ($property['type'] == 'select') : ?>

		<?php
		$modalities = array();
		
		if ($propertyId == 'place_id') foreach ($places as $place) {
			$modalities[$place->id] = $place->caption;
		} 
		elseif ($property['type'] == 'select') {
			foreach ($property['modalities'] as $modalityId => $modality) {
				$modalities[$modalityId] = $modality[$context->getLocale()];
			}
		}
		else {
			foreach ($context->getConfig($property['name'])['modalities'] as $modalityId => $modality) {
				$modalities[$modalityId] = $modality[$context->getLocale()];
			}
		}
		?>

		<label class="col-sm-6 control-label search"><?php echo $property['labels'][$context->getLocale()] ?></label>
		<div class="input-group search">
		    <span class="input-group-addon">
				<input type="checkbox" class="search_check" id="search_check_<?php echo $propertyId ?>">
			</span>
			<select id="search_<?php echo $propertyId ?>" class="form-control search_input">
				<option value=""></option>
		<?php var_dump($type); foreach ($modalities as $modalityId => $modalityLabel) : ?>
		    	<option value="<?php echo $modalityId ?>" <?php if ($propertyId == 'type' && $modalityId === $type) echo 'selected="selected"' ?>><?php echo $modalityLabel ?></option>
		<?php endforeach;?>
		    </select>
		</div>
	
	<?php elseif ($rendering == 'contains') : ?>
		<label class="col-sm-6 control-label search"><?php echo $property['labels'][$context->getLocale()] ?></label>
		<div class="input-group search">
		    <span class="input-group-addon">
				<input type="checkbox" class="search_check" id="search_check_<?php echo $propertyId ?>">
			</span>
			<input class="form-control" type="text" class="search_input" id="search_<?php echo $propertyId ?>" placeholder="<?php echo $this->translate('Contains', 'ppit-core', $context->getLocale()) ?>" />
		</div>

	<?php elseif ($rendering == 'range') : ?>

		<label class="col-sm-6 control-label search"><?php echo $property['labels'][$context->getLocale()] ?></label>
		<div class="input-group search">
		    <span class="input-group-addon">
				<input type="checkbox" class="search_check" id="search_check_min_<?php echo $propertyId ?>">
			</span>
	    	<input class="form-control" type="text" class="search_input" id="search_min_<?php echo $propertyId ?>" class="form-control" placeholder="<?php echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
		</div>

		<label class="col-sm-6 control-label search">&nbsp;</label>
		<div class="input-group search">
		    <span class="input-group-addon">
				<input type="checkbox" class="search_check" id="search_check_max_<?php echo $propertyId ?>">
			</span>
	    	<input class="form-control" type="text" class="search_input" id="search_max_<?php echo $propertyId ?>" class="form-control" placeholder="<?php echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
		</div>

	<?php endif;?>
<?php endforeach;?>

		<div class="col-sm-6">&nbsp;</div>
		
		<div class="col-sm-3">
    		<button type="button" class="form-control btn btn-default btn-xs" title="<?php echo $this->translate('Search', 'ppit-core', $context->getLocale()) ?>" id="search-button">
				<span class="glyphicon glyphicon-search"></span>
			</button>
		</div>
		<div class="col-sm-3 search">
    		<button type="button" class="form-control btn btn-default btn-xs" title="<?php echo $this->translate('Erase', 'ppit-core', $context->getLocale()) ?>" id="erase-button">
				<span class="glyphicon glyphicon-remove"></span>
			</button>
<?php if ($context->isDemoModeActive()) : ?>
				<a class="tip" href="#" title="<?php echo $context->getConfig('demo')['commitment/search/x'][$context->getLocale()] ?>">
				    <img src="<?php echo $this->basePath('img/tip.png') ?>" width="20" />
				</a>
<?php endif;?>
		</div>
		</div>

		<div class="col-md-6">
<?php if ($type) : ?>
			<div class="col-md-6 col-md-offset-3"><canvas id="chart"></canvas></div>
<?php endif;?>
		</div>

<!-- Add or update section -->
		<div style="background-color: #ffffff;" class="row">
			<div>&nbsp;</div>
			<div id="commitment-list-panel"></div>
		</div>
	</div>
</div>
