<div class="panel panel-default">
	<div class="panel-heading" style="background: <?php echo $context->getConfig('styleSheet')['panelHeadingBackground'] ?>; color: <?php echo $context->getConfig('styleSheet')['panelHeadingColor'] ?>">
		<strong>
			<?php echo $this->translate('Commitments', 'ppit-commitment', $context->getLocale());?>
			(<span id="mode-text"></span>)
		</strong>
	</div>
	<div class="panel-body">

<!-- Filters -->

		<div class="form-group">
			<label class="col-sm-5 control-label"><span class="glyphicon glyphicon-search"></span></label>
			<div class="col-sm-7">
	    		<button type="button" class="form-control btn btn-default btn-xs" title="<?php echo $this->translate('Erase', 'ppit-core', $context->getLocale()) ?>" id="erase-button">
					<span class="glyphicon glyphicon-remove"></span>
				</button>
			</div>
		</div>
		
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Status', 'ppit-core', $context->getLocale()) ?></label>
			<div class="col-sm-7">
	    		<select class="form-control" id="search_status">
	    			<option value=""><?php echo $this->translate('Status', 'ppit-core', $context->getLocale()) ?></option>
<?php foreach ($context->getConfig('commitment')['statuses'] as $statusId => $status) : ?>
	    			<option value="<?php echo $statusId ?>"><?php echo $status['labels'][$context->getLocale()] ?></option>
<?php endforeach;?>
	    		</select>
			</div>
		</div>
		
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Account', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
	    		<select class="form-control" id="search_account_id">
	    			<option value=""><-- <?php echo $this->translate('Please choose', 'ppit-core', $context->getLocale()) ?> --></option>
<?php foreach ($accounts as $account) : ?>
	    			<option value="<?php echo $account->id ?>"><?php echo $account->customer_name ?></option>
<?php endforeach;?>
	    		</select>
			</div>
		</div>
		
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Subscription', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
	    		<select class="form-control" id="search_subscription_id">
	    			<option value=""><-- <?php echo $this->translate('Please choose', 'ppit-core', $context->getLocale()) ?> --></option>
<?php foreach ($subscriptions as $subscription) : ?>
	    			<option value="<?php echo $subscription->id ?>"><?php echo $subscription->product_identifier ?></option>
<?php endforeach;?>
	    		</select>
			</div>
		</div>
	
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Amount', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_min_amount" class="form-control" placeholder="<?php echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-5 control-label">&nbsp;</label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_max_amount" class="form-control" placeholder="<?php echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

	<div><a id="add-criteria" href="#"><?php echo $this->translate('More criteria', 'ppit-core', $context->getLocale())?></a></div>
	<div id="search-area">
	
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Identifier', 'ppit-core', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input class="form-control" type="text" id="search_identifier" placeholder="<?php echo $this->translate('Contains', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>
	
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Quotation identifier', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input class="form-control" type="text" id="search_quotation_identifier" placeholder="<?php echo $this->translate('Contains', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>
		
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Invoice identifier', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input class="form-control" type="text" id="search_invoice_identifier" placeholder="<?php echo $this->translate('Contains', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Commitment date', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_min_commitment_date" class="form-control" placeholder="<?php echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-5 control-label">&nbsp;</label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_max_commitment_date" class="form-control" placeholder="<?php echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>
<!--		
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php //echo $this->translate('Retraction limit', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_min_retraction_limit" class="form-control" placeholder="<?php //echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-5 control-label">&nbsp;</label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_max_retraction_limit" class="form-control" placeholder="<?php //echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>
	
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php //echo $this->translate('Retraction date', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_min_retraction_date" class="form-control" placeholder="<?php //echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-5 control-label">&nbsp;</label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_max_retraction_date" class="form-control" placeholder="<?php //echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-5 control-label"><?php //echo $this->translate('Actual shipment', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_min_shipment_date" class="form-control" placeholder="<?php //echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-5 control-label">&nbsp;</label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_max_shipment_date" class="form-control" placeholder="<?php echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>
-->		
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Expected delivery', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_min_expected_delivery_date" class="form-control" placeholder="<?php echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-5 control-label">&nbsp;</label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_max_expected_delivery_date" class="form-control" placeholder="<?php echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>
		
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Actual delivery', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_min_delivery_date" class="form-control" placeholder="<?php echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-5 control-label">&nbsp;</label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_max_delivery_date" class="form-control" placeholder="<?php echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>
<!--		
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php //echo $this->translate('Actual commissioning', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_min_commissioning_date" class="form-control" placeholder="<?php //echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-5 control-label">&nbsp;</label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_max_commissioning_date" class="form-control" placeholder="<?php echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>
-->	
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Due date', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
	    		<input type="text" size="3" id="search_min_expected_invoice_date" class="form-control" placeholder="<?php echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-5 control-label">&nbsp;</label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_max_expected_invoice_date" class="form-control" placeholder="<?php echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>
		
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Invoicing date', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
	    		<input type="text" size="3" id="search_min_invoice_date" class="form-control" placeholder="<?php echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-5 control-label">&nbsp;</label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_max_invoice_date" class="form-control" placeholder="<?php echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>
		
<?php foreach ($context->getConfig('commitment')['properties'] as $propertyId => $property) : ?>
		
		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $property['labels'][$context->getLocale()] ?></label>
			<div class="col-sm-7">
				<input class="form-control" type="text" id="search_<?php echo $propertyId ?>" placeholder="<?php echo $this->translate('Contains', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-5 control-label">&nbsp;</label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_min_<?php echo $propertyId ?>" class="form-control" placeholder="<?php echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-5 control-label">&nbsp;</label>
			<div class="col-sm-7">
	    		<input class="form-control" type="text" id="search_max_<?php echo $propertyId ?>" class="form-control" placeholder="<?php echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
			</div>
		</div>

<?php endforeach;?>

	</div>

	    <div>&nbsp;</div>

<!-- Actions -->
	    <div>
	    		<button type="button" class="btn btn-default" title="<?php echo $this->translate('Export', 'ppit-core', $context->getLocale()) ?>" id="export-button">
					<span class="glyphicon glyphicon-cloud-download"></span>
					<span><?php echo $this->translate('Export', 'ppit-core', $context->getLocale())?></span>
				</button>
	    </div>
	    
		<div>&nbsp;</div>

<!-- Add or update section -->
		<div id="commitment-list-panel"></div>
	</div>
</div>
