<!-- Load the common form javascript functions -->
<?php echo $this->partial('/partials/common-form-js.phtml'); ?>

<?php
$title = $this->translate('P-Pit', 'ppit-core', $context->getLocale());
$this->headTitle($title);
echo $this->partial('/partials/header');
?>

<div class="container">

<!-- Front product 1 -->
<div class="row">

    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading front-page" style="background:  <?php echo $context->getConfig('styleSheet')['panelHeadingBackground'] ?>; color: <?php echo $context->getConfig('styleSheet')['panelHeadingColor'] ?>">
                <div><?php echo $this->translate('Payment', 'ppit-commitment', $context->getLocale()) ?></div>
            </div>
            <div class="panel-body">
       			<div>

<!-- Form header -->
<?php echo $error ?>
<?php echo $message ?>
				</div>
             </div>
        </div>
	</div>
</div>
