<?php if ($context->isDemoModeActive()) : ?>
		<a class="tip" href="#" title="<?php echo $context->getConfig('demo')['commitment/update'][$context->getLocale()] ?>">
		    <img src="<?php echo $this->basePath('img/tip.png') ?>" width="20" />
		</a>
<?php endif;?>

<?php if ($commitment->id && !$message) : ?>
		<button type="button" class="btn btn-default action-btn" id="commitment-update-anchor" title="<?php echo $this->translate('Update', 'ppit-core', $context->getLocale()) ?>" <?php if (in_array($commitment->credit_status, array('blocked', 'suspended', 'closed')) || in_array($commitment->status, array('invoiced', 'settled'))) echo 'disabled="disabled"' ?>>
			<span class="glyphicon glyphicon-edit"></span>
		</button>

		<button type="button" class="btn btn-default action-btn" id="commitment-delete-anchor" title="<?php echo $this->translate('Delete', 'ppit-core', $context->getLocale()) ?>" <?php if (!$commitment->isDeletable()) echo 'disabled="disabled"' ?>>
			<span class="glyphicon glyphicon-trash"></span>
		</button>

	<?php if ($commitment->status != 'invoiced' && $commitment->status != 'settled') : ?>
		<button type="button" class="btn btn-default action-btn" id="commitment-invoice-anchor" <?php if (in_array($commitment->credit_status, array('blocked', 'suspended', 'closed'))) echo 'disabled="disabled"' ?>>
			<?php echo $this->translate('Generate invoice', 'ppit-commitment', $context->getLocale()) ?>
		</button>
		<div class="form-group">
			<div class="alert alert-danger" id="commitment-invoice-alert" style="text-align: center">
				<strong><?php echo $this->translate('This action is irreversible. Please confirm.', 'ppit-core', $context->getLocale()) ?></strong>
			</div>
		</div>
	<?php endif;?>

	<?php if ($commitment->status == 'invoiced') : ?>
		<button type="button" class="btn btn-default action-btn" id="commitment-settle-anchor" <?php if (in_array($commitment->credit_status, array('blocked', 'suspended', 'closed'))) echo 'disabled="disabled"' ?>>
			<?php echo $this->translate('Register settlement', 'ppit-commitment', $context->getLocale()) ?>
		</button>
		<div class="form-group">
			<div class="alert alert-danger" id="commitment-settle-alert" style="text-align: center">
				<strong><?php echo $this->translate('This action is irreversible. Please confirm.', 'ppit-core', $context->getLocale()) ?></strong>
			</div>
		</div>
	<?php endif;?>
<?php endif;?>

<!-- Form header -->
<?php echo $this->partial('/partials/form-header', array(
		'update_time' => $commitment->update_time,
		'message' => $message,
		'error' => $error,
		'csrfForm' => $csrfForm,
		'context' => $context,
		'formId' => 'commitment-form',
));
?>

<?php if (!$commitment->id) : ?>
		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input name="submit" type="submit" id="commitment-up-submit-button" class="btn btn-warning" value="<?php echo $this->translate('Add', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>

<?php elseif ($action == 'update') : ?>
		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input name="submit" type="submit" id="commitment-up-submit-button" class="btn btn-warning" value="<?php echo $this->translate('Update', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>

<?php elseif ($action == 'delete') : ?>
		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input name="submit" type="submit" id="commitment-up-submit-button" class="btn btn-danger" value="<?php echo $this->translate('Delete', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>
<?php endif;?>

<?php 
if ($commitment->id && $action != 'update' || $message == 'OK') $isDisabled = true; else $isDisabled = false;
?>

		<div class="form-group" id="commitment-type_group">
			<label class="col-sm-5 control-label">* <?php echo $this->translate('Type', 'ppit-core', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<select class="form-control" id="commitment-type" disabled="disabled">
					<option />
	<?php foreach ($context->getConfig('commitment/types')['modalities'] as $typeId => $typeDef) : ?>
					<option value="<?php echo $typeId ?>" <?php if ($commitment->type == $typeId) echo 'selected="selected"' ?>><?php echo $typeDef[$context->getLocale()] ?></option>
	<?php endforeach;?>
				</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="commitment-type_error"></p></div>
		</div>

<?php foreach ($updatePage as $propertyId => $options) : ?>
	<?php $property = $configProperties[$propertyId] ?>
	
		<div class="form-group" id="commitment-<?php echo (($property['type'] == 'date' || $property['type'] == 'number') ? 'input_' : '').$propertyId ?>_group">
			<label class="col-sm-5 control-label"><?php if ($options['mandatory']) echo '* ' ?><?php echo $property['labels'][$context->getLocale()] ?></label>
			<div class="col-sm-7">

	<?php if ($propertyId == 'account_id') : ?>
				<select class="form-control" id="commitment-<?php echo $propertyId ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?>>
	    			<option />
		<?php foreach ($accounts as $account) : ?>
	    			<option value="<?php echo $account->id ?>" <?php if ($account->id == $commitment->account_id) echo 'selected="selected"' ?>><?php echo $account->name ?></option>
		<?php endforeach;?>
				</select>

	<?php elseif ($property['type'] == 'date') : ?>
				<input type="hidden" id="commitment-<?php echo $propertyId ?>" />
				<input class="form-control" id="input_commitment-<?php echo $propertyId ?>" value="<?php echo $context->decodeDate($commitment->properties[$propertyId]) ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />

	<?php elseif ($property['type'] == 'number') : ?>
				<input type="hidden" id="commitment-<?php echo $propertyId ?>" />
				<input class="form-control" id="input_commitment-<?php echo $propertyId ?>" value="<?php echo $context->formatFloat($commitment->properties[$propertyId], 2) ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />

	<?php elseif ($property['type'] == 'textarea') : ?>
				<textarea class="form-control" id="commitment-<?php echo $propertyId ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?>><?php echo $commitment->properties[$propertyId] ?></textarea>

	<?php elseif ($property['type'] == 'select') : ?>
				<select class="form-control" id="commitment-<?php echo $propertyId ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?>>
	    			<option />
		<?php foreach ($property['modalities'] as $key => $labels) : ?>
	    			<option value="<?php echo $key ?>" <?php if ($commitment->properties[$propertyId] == $key) echo 'selected="selected"' ?>><?php echo $labels[$context->getLocale()] ?></option>
		<?php endforeach;?>
				</select>
	
	<?php else : ?>
				<input class="form-control" id="commitment-<?php echo $propertyId ?>" value="<?php echo $commitment->properties[$propertyId] ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />

	<?php endif;?>
			</div>
			<div class="col-sm-12"><p class="help-block" id="<?php echo (($property['type'] == 'date' || $property['type'] == 'number') ? 'input_' : '').'commitment-'.$propertyId ?>_error"></p></div>
		</div>

<?php endforeach;?>

<?php if (!$commitment->id) : ?>
		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input name="submit" type="submit" id="commitment-submit-button" class="btn btn-warning" value="<?php echo $this->translate('Add', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>

<?php elseif ($action == 'update') : ?>
		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input name="submit" type="submit" id="commitment-submit-button" class="btn btn-warning" value="<?php echo $this->translate('Update', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>

<?php elseif ($action == 'delete') : ?>
		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input name="submit" type="submit" id="commitment-submit-button" class="btn btn-danger" value="<?php echo $this->translate('Delete', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>
<?php endif;?>
		
		</form>
