<!-- 
/**
 * PpitCore V1.0 (https://github.com/p-pit/PpitCore)
 *
 * @link      https://github.com/p-pit/PpitCore
 * @copyright Copyright (c) 2016 Bruno Lartillot
 * @license   https://github.com/p-pit/PpitCore/blob/master/license.txt GNU-GPL license
 */
-->

<div class="panel panel-default">
	<div class="panel-heading" style="background: #006179; color: #FFF">
		<strong><em>
			<?php 
			$title = $this->translate('P-Pit', 'ppit-core', $context->getLocale());
			echo $title;
			?>
		</em></strong>
	</div>
	<div class="panel-body">

<!-- Add or update section -->
		<div id="credit-list-panel"></div>
	</div>
</div>
