
function connectCommitmentMessageRemoveIcon(type, id, target)
{
	$('#' + id).click(function () {
		$('#' + target).hide();
		getCommitmentMessageList(type, 'id', 'DESC');
	});
}

function sortCommitmentMessageList(type, criterion) {
	var dir;
	ascCriterion = $('.glyphicon-triangle-top').first().parent().attr('id');
	descCriterion = $('.glyphicon-triangle-bottom').first().parent().attr('id');
	if (criterion + '-anchor' == ascCriterion) dir = 'DESC'; else dir = 'ASC';
	getCommitmentMessageList(type, criterion, dir);
}

function connectAddPhotographForm()
{
	var validity = true;

	// Folder
	val = $('#folder').val();
	if (!val) {
		renderElement("folder", "<?php echo $this->translate('Please select a value', 'ppit-core', $context->getLocale()) ?>");
		validity = false;
	}

	if (validity) {
		var formData = new FormData();
		formData.append('folder', $('#folder').val());
		var fileSelect = document.getElementById('attachment');
		if (fileSelect) {
			var files = fileSelect.files;
			for (var i = 0; i < files.length; i++) {
				var file = files[i];
				formData.append('attachment', file, file.name);
			}
		}
		var xhttp = new XMLHttpRequest();
		var route, target;
		route = '<?php echo $this->url('commitmentMessage/addPhotograph') ?>';
		xhttp.open('POST', route, true);
		xhttp.onload = function () {
			if (xhttp.readyState == 4 <?php if (!$context->getConfig()['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
				$('#form_action').html(xhttp.responseText);
				$('#remove-anchor').click(function () { 
					$('#form_action').hide();
					$('#add-photograph-anchor').removeClass("btn-primary").addClass("btn-default");
				});
			}
		};
		xhttp.send(formData);
	}
	else return false;
}

function getAddPhotograph() {

	var xhttp = new XMLHttpRequest();
	var route = '<?php echo $this->url('commitmentMessage/addPhotograph') ?>';
	xhttp.open('GET', route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
<?php endif;?>
			$('#form_action').show();
			$('#form_action').html(xhttp.responseText);
			$('#remove-anchor').click(function () { 
				$('#form_action').hide();
				$('#add-photograph-anchor').removeClass("btn-primary").addClass("btn-default");
			});
			$('#submit-button').click(function () { connectAddPhotographForm(); });
<?php if (!$config['isTraceActive']) : ?>
			}
<?php endif;?>
		}
	}
	xhttp.send();

	// Highlight the clicked button (and only it in its class)
	$('.action-btn').removeClass("btn-primary").addClass("btn-default");
	$('#add-photograph-anchor').removeClass("btn-default").addClass("btn-primary");
}

// Load the list
function getCommitmentMessageList(type, major, dir) {

	// Execute the ajax request
	route = '<?php echo $this->url('commitmentMessage/search') ?>' + '?major=' + major + ((dir =='ASC') ? '&dir=ASC' : '&dir=DESC');
 	xhttp = new XMLHttpRequest();
	xhttp.open("GET", route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>
			document.getElementById('index_action').innerHTML = xhttp.responseText;
			// Connect the sort anchors
			$('.ppit-sort-anchor').each(function () {
				$(this).click(function () {
					sortCommitmentMessageList(type, $(this).attr('id').split('-')[0]);
				});
			});

			$('#commitment-message-add-anchor').click(function () { showCommitmentMessageDetail(type, '0', 'import'); });
			$('#add-photograph-anchor').click(function () { getAddPhotograph(); });
			
			// Connect the detail anchors
			$('.commitment-message-submit-anchor').each(function () {
				$(this).click(function () {
					showCommitmentMessageDetail(type, $(this).attr('id').split('_')[1], 'submit');
				});
			});
			$('.commitment-message-import-anchor').each(function () {
				$(this).click(function () {
					showCommitmentMessageDetail(type, $(this).attr('id').split('_')[1], 'process');
				});
			});
	<?php if (!$config['isTraceActive']) : ?>
			}
	<?php endif;?>
		}
	}
	xhttp.send();
}

// MESSAGES

// Import panel
<?php $properties = array(
		'type' => array('type' => 'select', 'mandatory' => true),
		'files' => array('type' => 'file'),
) ?>
<?php echo $this->partial('/partials/ppit-commitment-message-detail-scripts', array(
		'context' => $context,
		'action' => 'import',
		'route' => 'commitmentMessage/import',
		'properties' => $properties,
)) ?>

// Submit panel
<?php $properties = array(
		'update_time' => array('type' => 'hidden'),
) ?>
<?php echo $this->partial('/partials/ppit-commitment-message-detail-scripts', array(
		'context' => $context,
		'action' => 'submit',
		'route' => 'commitmentMessage/submit',
		'properties' => $properties,
)) ?>

// Process panel
<?php $properties = array(
) ?>
<?php echo $this->partial('/partials/ppit-commitment-message-detail-scripts', array(
		'context' => $context,
		'action' => 'process',
		'route' => 'commitmentMessage/process',
		'properties' => $properties,
)) ?>

function showCommitmentMessageDetail(type, id, action)
{
	$('#form_action').show();
	$(location).attr('hash', 'form_action');

	// Execute the ajax request
	xhttp = new XMLHttpRequest();
	var route;
	if (action == 'import') route = '<?php echo $this->url('commitmentMessage/import') ?>';
	else if (action == 'submit') route = '<?php echo $this->url('commitmentMessage/submit') ?>/' + id;
	else if (action == 'process') route = '<?php echo $this->url('commitmentMessage/process') ?>/' + id;
	xhttp.open("GET", route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>
			document.getElementById('form_action').innerHTML = xhttp.responseText;

			connectCommitmentMessageRemoveIcon(type, 'remove-anchor', 'form_action');
			connectCommitmentMessageRemoveIcon(type, 'return-anchor', 'form_action');
			connectCommitmentMessageRemoveIcon(type, 'cancel-anchor', 'form_action');
			if (action =='import') connectimportForm(0);
			else if (action =='submit') connectsubmitForm(id);
			else if (action =='process') connectprocessForm(id);
	<?php if (!$config['isTraceActive']) : ?>
			}
	<?php endif;?>
		}
	}
	xhttp.send();
}

function activateCommitmentMessage(type) {
	// Load the search panel and highlight the menu entry
	loadPanel('index_action', '<?php echo $this->url('commitmentMessage/search') ?>');
	$('.menu-btn').removeClass("btn-primary").addClass("btn-default");
	$('#message-anchor').removeClass("btn-default").addClass("btn-primary");

	getCommitmentMessageList(type, 'id', 'DESC');
}
$('#commitmentMessage-anchor').click(function () { activateCommitmentMessage(''); });
