
function connectRemoveIcon(id, target)
{
	$('#' + id).click(function () {
		$('#' + target).hide();
		filterAccountList();
	});
}

function getParams() {

	var params = '?', todo = true;

<?php foreach ($context->getConfig('commitmentAccount/search'.(($type) ? '/'.$type : ''))['main'] as $propertyId => $rendering) : ?>

	<?php if ($rendering == 'range') : ?>
	
	var min_<?php echo $propertyId ?> = document.getElementById('search_min_<?php echo $propertyId ?>').value;
	if (min_<?php echo $propertyId ?>) min_<?php echo $propertyId ?> = encodeDate(min_<?php echo $propertyId ?>);
	if (min_<?php echo $propertyId ?>.length >= 2) { params += 'min_<?php echo $propertyId ?>=' + min_<?php echo $propertyId ?> + '&'; todo = false; }

	var max_<?php echo $propertyId ?> = document.getElementById('search_max_<?php echo $propertyId ?>').value;
	if (max_<?php echo $propertyId ?>) max_<?php echo $propertyId ?> = encodeDate(max_<?php echo $propertyId ?>);
	if (max_<?php echo $propertyId ?>.length >= 2) { params += 'max_<?php echo $propertyId ?>=' + max_<?php echo $propertyId ?> + '&'; todo = false; }

	<?php elseif ($rendering == 'select') : ?>

	var <?php echo $propertyId ?> = document.getElementById('search_<?php echo $propertyId ?>').value;
	if (<?php echo $propertyId ?>) { params += '<?php echo $propertyId ?>=' + <?php echo $propertyId ?> + '&'; todo = false; }

	<?php else : ?>

	var <?php echo $propertyId ?> = document.getElementById('search_<?php echo $propertyId ?>').value;
	if (<?php echo $propertyId ?>.length >= 2) { params += '<?php echo $propertyId ?>=' + <?php echo $propertyId ?> + '&'; todo = false; }
	
	<?php endif;?>

<?php endforeach;?>

<?php foreach ($context->getConfig('commitmentAccount/search'.(($type) ? '/'.$type : ''))['more'] as $propertyId => $rendering) : ?>

	<?php if ($rendering == 'range') : ?>
	
	var min_<?php echo $propertyId ?> = document.getElementById('search_min_<?php echo $propertyId ?>').value;
	if (min_<?php echo $propertyId ?>) min_<?php echo $propertyId ?> = encodeDate(min_<?php echo $propertyId ?>);
	if (min_<?php echo $propertyId ?>.length >= 2) { params += 'min_<?php echo $propertyId ?>=' + min_<?php echo $propertyId ?> + '&'; todo = false; }

	var max_<?php echo $propertyId ?> = document.getElementById('search_max_<?php echo $propertyId ?>').value;
	if (max_<?php echo $propertyId ?>) max_<?php echo $propertyId ?> = encodeDate(max_<?php echo $propertyId ?>);
	if (max_<?php echo $propertyId ?>.length >= 2) { params += 'max_<?php echo $propertyId ?>=' + max_<?php echo $propertyId ?> + '&'; todo = false; }

	<?php elseif ($rendering == 'select') : ?>

	var <?php echo $propertyId ?> = document.getElementById('search_<?php echo $propertyId ?>').value;
	if (<?php echo $propertyId ?>) { params += '<?php echo $propertyId ?>=' + <?php echo $propertyId ?> + '&'; todo = false; }
	
	<?php else : ?>

	var <?php echo $propertyId ?> = document.getElementById('search_<?php echo $propertyId ?>').value;
	if (<?php echo $propertyId ?>.length >= 2) { params += '<?php echo $propertyId ?>=' + <?php echo $propertyId ?> + '&'; todo = false; }
	
	<?php endif;?>

<?php endforeach;?>

	<?php
	$todoTitle = (isset ($context->getConfig('commitmentAccount/search'.(($type) ? '/'.$type : ''))['todoTitle']) ? $context->getConfig('commitmentAccount/search'.(($type) ? '/'.$type : ''))['todoTitle'][$context->getLocale()] : $this->translate('active', 'ppit-core', $context->getLocale()));
	$searchTitle = (isset ($context->getConfig('commitmentAccount/search'.(($type) ? '/'.$type : ''))['searchTitle']) ? $context->getConfig('commitmentAccount/search'.(($type) ? '/'.$type : ''))['searchTitle'][$context->getLocale()] : $this->translate('search', 'ppit-core', $context->getLocale()));
	?>
	$('#mode-text').text((todo) ? '<?php echo $todoTitle ?>' : '<?php echo $searchTitle ?>');
	if (!todo) $('#limit').val('');

	return params;
}

// Export the list
function exportAccountList() {

	var params = getParams();
	document.location.href = '<?php echo $this->url('commitmentAccount/export', array('entry' => $entry, 'type' => $type)) ?>' + params;
}

function eraseAccountSearch() {

<?php foreach ($context->getConfig('commitmentAccount/search'.(($type) ? '/'.$type : ''))['main'] as $propertyId => $rendering) : ?>

	<?php if ($rendering == 'range') : ?>
	$('#search_min_<?php echo $propertyId ?>').val('');
	$('#search_max_<?php echo $propertyId ?>').val('');

	<?php else : ?>
	$('#search_<?php echo $propertyId ?>').val('');
	
	<?php endif;?>

<?php endforeach;?>

<?php foreach ($context->getConfig('commitmentAccount/search'.(($type) ? '/'.$type : ''))['more'] as $propertyId => $rendering) : ?>

	<?php if ($rendering == 'range') : ?>
	$('#search_min_<?php echo $propertyId ?>').val('');
	$('#search_max_<?php echo $propertyId ?>').val('');

	<?php else : ?>
	$('#search_<?php echo $propertyId ?>').val('');
	
	<?php endif;?>

<?php endforeach;?>

	getAccountList(getParams(), '<?php echo $context->getConfig('commitmentAccount'.(($type) ? '/'.$type : ''))['order'] ?>', 'ASC');
}

function sortAccountList(criterion) {

	var dir;
	ascCriterion = $('.glyphicon-triangle-top').first().parent().attr('id');
	descCriterion = $('.glyphicon-triangle-bottom').first().parent().attr('id');
	if (criterion + '-anchor' == ascCriterion) dir = 'DESC'; else dir = 'ASC';
	getAccountList(getParams(), criterion, dir);
}

function filterAccountList() {

	ascCriterion = $('.glyphicon-triangle-top').first().parent().attr('id');
	descCriterion = $('.glyphicon-triangle-bottom').first().parent().attr('id');
	if (ascCriterion) {
		criterion = ascCriterion.split('-')[0];
		dir = 'ASC';
	}
	else {
		criterion = descCriterion.split('-')[0];
		dir = 'ASC';
	}
	getAccountList(getParams(), criterion, dir);
}

function connectAccountSearchInputs() {

	$('#export-button').click(function () { exportAccountList(); });
	
	$('#erase-button').unbind();
	$('#erase-button').click(function () { eraseAccountSearch(); });

<?php foreach ($context->getConfig('commitmentAccount/search'.(($type) ? '/'.$type : ''))['main'] as $propertyId => $rendering) : ?>

	<?php if ($rendering == 'range') : ?>
	$('#search_min_<?php echo $propertyId ?>').keyup(function () { filterAccountList(); });
	$('#search_max_<?php echo $propertyId ?>').keyup(function () { filterAccountList(); });

		<?php if ($context->getConfig('commitmentAccount'.(($type) ? '/'.$type : ''))['properties'][$propertyId]['type'] == 'date') : ?>
	$("#search_min_<?php echo $propertyId ?>").datepicker();
	$("#search_max_<?php echo $propertyId ?>").datepicker();
	$('#search_min_<?php echo $propertyId ?>').change(function () { filterAccountList(); });
	$('#search_max_<?php echo $propertyId ?>').change(function () { filterAccountList(); });
		<?php endif;?>
	
	<?php elseif ($rendering == 'select') : ?>
		$('#search_<?php echo $propertyId ?>').change(function () { filterAccountList(); });
	
	<?php else : ?>
		$('#search_<?php echo $propertyId ?>').keyup(function () { filterAccountList(); });

		<?php if ($context->getConfig('commitmentAccount'.(($type) ? '/'.$type : ''))['properties'][$propertyId]['type'] == 'date') : ?>
	$("#search_<?php echo $propertyId ?>").datepicker();
	$('#search_<?php echo $propertyId ?>').change(function () { filterAccountList(); });
		<?php endif;?>

	<?php endif;?>

<?php endforeach;?>

<?php foreach ($context->getConfig('commitmentAccount/search'.(($type) ? '/'.$type : ''))['more'] as $propertyId => $rendering) : ?>

	<?php if ($rendering == 'range') : ?>
	$('#search_min_<?php echo $propertyId ?>').keyup(function () { filterAccountList(); });
	$('#search_max_<?php echo $propertyId ?>').keyup(function () { filterAccountList(); });

		<?php if ($context->getConfig('commitmentAccount'.(($type) ? '/'.$type : ''))['properties'][$propertyId]['type'] == 'date') : ?>
	$("#search_min_<?php echo $propertyId ?>").datepicker();
	$("#search_max_<?php echo $propertyId ?>").datepicker();
	$('#search_min_<?php echo $propertyId ?>').change(function () { filterAccountList(); });
	$('#search_max_<?php echo $propertyId ?>').change(function () { filterAccountList(); });
		<?php endif;?>
	
	<?php elseif ($rendering == 'select') : ?>
		$('#search_<?php echo $propertyId ?>').change(function () { filterAccountList(); });

	<?php else : ?>
		$('#search_<?php echo $propertyId ?>').keyup(function () { filterAccountList(); });

		<?php if ($context->getConfig('commitmentAccount'.(($type) ? '/'.$type : ''))['properties'][$propertyId]['type'] == 'date') : ?>
	$("#search_<?php echo $propertyId ?>").datepicker();
	$('#search_<?php echo $propertyId ?>').change(function () { filterAccountList(); });
		<?php endif;?>
		
	<?php endif;?>

<?php endforeach;?>
}

// Load the list
function getAccountList(params, major, dir) {		

	// Execute the ajax request
	route = '<?php echo $this->url('commitmentAccount/list', array('entry' => $entry, 'type' => $type)) ?>' + params + '&major=' + major + ((dir =='ASC') ? '&dir=ASC' : '&dir=DESC') + '&limit=' + $('#limit').val();
	xhttp = new XMLHttpRequest();
	xhttp.open("GET", route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>
			document.getElementById('account-list-panel').innerHTML = xhttp.responseText;
			
			$(function () {
			    $('.tip').tooltip({
			        content: function () {
			            return $(this).prop('title');
			        }
			    });
			});
			
			// Connect the sort anchors
			$('.ppit-sort-anchor').each(function () {
				$(this).click(function () {
					sortAccountList($(this).attr('id').split('-')[0]);
				});
			});

			// Connect the more anchor
			$('#account-more-anchor').click(function () {
				$('#limit').val('');
				filterAccountList();
			});

			// Able the group action button
			$('.account-checkbox').click(function () {
				$('.account-group-anchor').removeAttr('disabled');
			});

			// Connect the check all checkbox
			$('#account-checkbox').click(function () {
				var current = document.getElementById('account-checkbox').checked;
				var accountNumber = $('#account-number').val();
				document.getElementById('down-account-checkbox').checked = (current) ? true : false;
				for (i = 0; i < accountNumber; i++) {
					document.getElementById('account-checkbox_' + i).checked = (current) ? true : false;
				}
			});
			$('#down-account-checkbox').click(function () {
				var current = document.getElementById('down-account-checkbox').checked;
				var accountNumber = $('#account-number').val();
				document.getElementById('account-checkbox').checked = (current) ? true : false;
				for (i = 0; i < accountNumber; i++) {
					document.getElementById('account-checkbox_' + i).checked = (current) ? true : false;
				}
			});
			
			// Connect the grouped actions anchors
			$('.account-group-anchor').each(function () {
				$(this).click(function () {
					getAccountGroup();
				});
			});
			
			// Connect the detail anchors
			$('.account-detail-anchor').each(function () {
				$(this).click(function () {
					getAccountDetail($(this).attr('id').split('_')[1]);
				});
			});
			
			// Connect the register anchor
			$('#account-register-anchor').click(function () {
				$('#iframe_action').show();
				$('.index-btn').removeClass("btn-primary").addClass("btn-default");
				$('#account-register-anchor').removeClass("btn-default").addClass("btn-primary");
			});
<?php if (!$config['isTraceActive']) : ?>
			}
<?php endif;?>
		}
	}
	xhttp.send();
}

function connectAuditPanel()
{
	$('#audit-panel').hide();
	$('#audit-label').click(function () {
		if ($('#audit-label').text() == '<?php echo $this->translate('Show', 'ppit-core', $context->getLocale()) ?>') {
			$('#audit-panel').show();
			$('#audit-label').text('<?php echo $this->translate('Mask', 'ppit-core', $context->getLocale()) ?>');
		}
		else {
			$('#audit-panel').hide();
			$('#audit-label').text('<?php echo $this->translate('Show', 'ppit-core', $context->getLocale()) ?>');
		}
	});
}

<?php 
$properties = array();

foreach ($context->getConfig('commitmentAccount/update'.(($type) ? '/'.$type : '')) as $propertyId => $options) {
	$property = $context->getConfig('commitmentAccount'.(($type) ? '/'.$type : ''))['properties'][$propertyId];
	if ($propertyId != 'place_id' && $property['type'] == 'repository') $property = $context->getConfig($property['definition']);
	if ($options && (!array_key_exists('readonly', $options) || !$options['readonly']) && $property['type'] != 'title') {
		$properties[$propertyId] = array('type' => $property['type'], 'mandatory' => $options['mandatory'], 'maxSize' => ($property['type'] == 'textarea' || $property['type'] == 'log') ? 2047 : 255);
	}
}

$properties['update_time'] = array('type' => 'hidden');

echo $this->partial('/partials/check-update-properties', array('entity' => 'Account', 'context' => $context, 'properties' => $properties)) 
?>

function connectAccountUpdateForm(id, action)
{

<?php foreach ($properties as $propertyId => $property) : ?>
	<?php if ($property['type'] == 'date') : ?>
		$('#input_<?php echo $propertyId ?>').datepicker();
	<?php elseif ($property['type'] == 'time') : ?>
		$('#<?php echo $propertyId ?>').timepicker({ 'timeFormat':'H:i:s', 'step': 15, 'scrollDefault': 'now' });
	<?php endif;?>
<?php endforeach ?>

	var form = document.getElementById('ppit-form');
	form.onsubmit = function(event) {
		
		event.preventDefault();
	
		// Check validity
		var validity;
		if (action == 'delete') validity = true;
		else {
			validity = checkAccountUpdateProperties(id);
			if ($('#new_password').val() != $('#new_password2').val()) {
				renderElement("new_password", "<?php echo $this->translate('Both new passwords should be identical', 'ppit-core', $context->getLocale()) ?>");
				validity = false;
			}
		}

		if (validity) {
		
			// Create a new FormData object.
			var formData = new FormData();
			
			// Get the properties values
<?php foreach ($properties as $propertyId => $property) : ?>
	<?php if (in_array($property['type'], array('input', 'date', 'time', 'textarea', 'log', 'select', 'repository', 'number', 'email', 'phone', 'hidden'))) : ?>
				formData.append('<?php echo $propertyId ?>', document.getElementById('<?php echo $propertyId ?>').value);

	<?php elseif ($property['type'] == 'checkbox') : ?>
				formData.append('<?php echo $propertyId ?>', ((document.getElementById('<?php echo $propertyId ?>').checked) ? 1 : 0));

	<?php elseif ($property['type'] == 'photo') : ?>
				var fileSelect = document.getElementById('<?php echo $propertyId ?>');
				if (fileSelect) {
					var files = fileSelect.files;
					for (var i = 0; i < files.length; i++) {
						var file = files[i];
						formData.append('<?php echo $propertyId ?>', file, file.name);
					}
				}

	<?php endif ?>

<?php endforeach ?>

			var xhttp = new XMLHttpRequest();
			var route, target;
			route = '<?php echo $this->url('commitmentAccount/update') ?>/' + id + '<?php echo (($type) ? '/'.$type : '') ?>';
			if (action) route += '?act=' + action;
			target = 'account-update-panel';
			xhttp.open('POST', route, true);
			// Set up a handler for when the request finishes.
			xhttp.onload = function () {
				if (xhttp.readyState == 4 <?php if (!$context->getConfig()['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
					document.getElementById(target).innerHTML = xhttp.responseText;
					filterAccountList();
					connectAccountUpdateForm(id, action);
					$('.action-btn').removeClass('btn-primary').addClass('btn-default');
				}
			};
			xhttp.send(formData);
		}
		else return false;
	}
}

function getAccountUpdate(id, action) {

	var xhttp = new XMLHttpRequest();
	var route = '<?php echo $this->url('commitmentAccount/update') ?>/' + id + '<?php echo (($type) ? '/'.$type : '') ?>';
	if (action) route += '?act=' + action;

	xhttp.open('GET', route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>
			document.getElementById('account-update-panel').innerHTML = xhttp.responseText;
			if (id == 0) $('#status').val('<?php echo $status ?>');
			
			$(function () {
			    $('.tip').tooltip({
			        content: function () {
			            return $(this).prop('title');
			        }
			    });
			});

			if (id) {
				$('#account-update-anchor').click(function () { getAccountUpdate(id, 'update'); });
				$('#account-delete-anchor').click(function () { getAccountUpdate(id, 'delete'); });
			}
			else $('#account-add-anchor').click(function () { getAccountUpdate(id, 'add'); });
			
			connectAccountUpdateForm(id, action);
			
<?php if (!$config['isTraceActive']) : ?>
			}
<?php endif;?>
		}
	}
	xhttp.send();

	// Highlight the clicked button (and only it in its class)
	$('.action-btn').removeClass("btn-primary").addClass("btn-default");
	if (action == 'update') $('#account-update-anchor').removeClass("btn-default").addClass("btn-primary");
	else if (action == 'delete') $('#account-delete-anchor').removeClass("btn-default").addClass("btn-primary");
}

<?php 
$properties = array();
$properties['username'] = array('type' => 'input', 'mandatory' => false, 'maxSize' => 255);
$properties['state'] = array('type' => 'checkbox');
$properties['is_notified'] = array('type' => 'checkbox');
$properties['new_password'] = array('type' => 'input', 'mandatory' => false, 'maxSize' => 255);
$properties['locale'] = array('type' => 'select', 'mandatory' => false);
$properties['update_time'] = array('type' => 'hidden');

echo $this->partial('/partials/check-update-properties', array('entity' => 'User', 'context' => $context, 'properties' => $properties)) 
?>

function connectUserUpdateForm(id, action)
{

<?php foreach ($properties as $propertyId => $property) : ?>
	<?php if ($property['type'] == 'date') : ?>
		$('#input_<?php echo $propertyId ?>').datepicker();
	<?php elseif ($property['type'] == 'time') : ?>
		$('#<?php echo $propertyId ?>').timepicker({ 'timeFormat': 'H:i:s' });
	<?php endif;?>
<?php endforeach ?>

	var form = document.getElementById('ppit-form');
	form.onsubmit = function(event) {
		
		event.preventDefault();
	
		// Check validity
		var validity = checkUserUpdateProperties(id);
		if ($('#new_password').val() != $('#new_password2').val()) {
			renderElement("new_password", "<?php echo $this->translate('Both new passwords should be identical', 'ppit-core', $context->getLocale()) ?>");
			validity = false;
		}

		if (validity) {
		
			// Create a new FormData object.
			var formData = new FormData();
			
			// Get the properties values
<?php foreach ($properties as $propertyId => $property) : ?>
	<?php if (in_array($property['type'], array('input', 'date', 'time', 'textarea', 'log', 'select', 'repository', 'number', 'email', 'phone', 'hidden'))) : ?>
				formData.append('<?php echo $propertyId ?>', document.getElementById('<?php echo $propertyId ?>').value);

	<?php elseif ($property['type'] == 'checkbox') : ?>
				formData.append('<?php echo $propertyId ?>', ((document.getElementById('<?php echo $propertyId ?>').checked) ? 1 : 0));

	<?php endif ?>

<?php endforeach ?>

			var xhttp = new XMLHttpRequest();
			var route, target;
			route = '<?php echo $this->url('commitmentAccount/updateUser', array('type' => $type)) ?>/' + id;
			if (action) route += '/' + action;
			target = 'account-update-panel';
			xhttp.open('POST', route, true);
			// Set up a handler for when the request finishes.
			xhttp.onload = function () {
				if (xhttp.readyState == 4 <?php if (!$context->getConfig()['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
					document.getElementById(target).innerHTML = xhttp.responseText;
					connectUserUpdateForm(id, action);
					$('.action-btn').removeClass('btn-primary').addClass('btn-default');
				}
			};
			xhttp.send(formData);
		}
		else return false;
	}
}

function getUserUpdate(id, action) {

	var xhttp = new XMLHttpRequest();
	var route = '<?php echo $this->url('commitmentAccount/updateUser', array('type' => $type)) ?>/' + id;
	if (action) route += '/' + action;

	xhttp.open('GET', route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>
			document.getElementById('account-update-panel').innerHTML = xhttp.responseText;

			if (id) {
				$('#account-update-anchor').click(function () { getAccountUpdate(id, 'update'); });
				$('#account-delete-anchor').click(function () { getAccountUpdate(id, 'delete'); });
			}
			else $('#account-add-anchor').click(function () { getAccountUpdate(id, 'add'); });
			
			connectUserUpdateForm(id, action);
			
<?php if (!$config['isTraceActive']) : ?>
			}
<?php endif;?>
		}
	}
	xhttp.send();

	// Highlight the clicked button (and only it in its class)
	$('.action-btn').removeClass("btn-primary").addClass("btn-default");
	if (action == 'update') $('#account-update-anchor').removeClass("btn-default").addClass("btn-primary");
	else if (action == 'delete') $('#account-delete-anchor').removeClass("btn-default").addClass("btn-primary");
}

<?php 
$properties = array();
$properties['contact_status'] = array('type' => 'select', 'mandatory' => false);

foreach ($context->getConfig('commitmentAccount/updateContact'.(($type) ? '/'.$type : '')) as $propertyId => $options) {
	$property = $context->getConfig('vcard/properties')[$propertyId];
	$properties[$propertyId] = array('type' => $property['type'], 'mandatory' => $options['mandatory'], 'maxSize' => ($property['type'] == 'textarea' || $property['type'] == 'log') ? 2047 : 255);
}

$properties['update_time'] = array('type' => 'hidden');

echo $this->partial('/partials/check-update-properties', array('entity' => 'Contact', 'context' => $context, 'properties' => $properties)) 
?>

<?php foreach (array('contact_1', 'user', 'contact_2', 'contact_3', 'contact_4') as $contactNumber) : ?>

function connect<?php echo $contactNumber ?>UpdateForm(id, action)
{
<?php foreach ($properties as $propertyId => $property) : ?>
	<?php if ($property['type'] == 'date') : ?>
		$('#input_<?php echo $propertyId ?>').datepicker();
	<?php elseif ($property['type'] == 'time') : ?>
		$('#<?php echo $propertyId ?>').timepicker({ 'timeFormat': 'H:i:s' });
	<?php endif;?>
<?php endforeach ?>

	var form = document.getElementById('ppit-form');
	form.onsubmit = function(event) {
		
		event.preventDefault();
	
		// Check validity
		var validity = checkContactUpdateProperties(id);

		if (validity) {
		
			// Create a new FormData object.
			var formData = new FormData();
			
			// Get the properties values
	<?php foreach ($properties as $propertyId => $property) : ?>
		<?php if (in_array($property['type'], array('input', 'date', 'time', 'textarea', 'log', 'select', 'repository', 'number', 'email', 'phone', 'hidden'))) : ?>
				formData.append('<?php echo $propertyId ?>', document.getElementById('<?php echo $propertyId ?>').value);

		<?php elseif ($property['type'] == 'checkbox') : ?>
				formData.append('<?php echo $propertyId ?>', ((document.getElementById('<?php echo $propertyId ?>').checked) ? 1 : 0));

		<?php elseif ($property['type'] == 'photo') : ?>
				var fileSelect = document.getElementById('<?php echo $propertyId ?>');
				if (fileSelect) {
					var files = fileSelect.files;
					for (var i = 0; i < files.length; i++) {
						var file = files[i];
						formData.append('order_form', file, file.name);
					}
				}

		<?php endif ?>

	<?php endforeach ?>

			var xhttp = new XMLHttpRequest();
			var route, target;
			route = '<?php echo $this->url('commitmentAccount/updateContact', array('type' => $type, 'contactNumber' => $contactNumber)) ?>/' + id;
			if (action) route += '/' + action;
			target = 'account-update-panel';
			xhttp.open('POST', route, true);
			// Set up a handler for when the request finishes.
			xhttp.onload = function () {
				if (xhttp.readyState == 4 <?php if (!$context->getConfig()['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
					document.getElementById(target).innerHTML = xhttp.responseText;
				}
			};
			xhttp.send(formData);
		}
		else return false;
	}
}

function get<?php echo $contactNumber ?>Update(id, action) {
	
	var xhttp = new XMLHttpRequest();
	var route = '<?php echo $this->url('commitmentAccount/updateContact', array('type' => $type, 'contactNumber' => $contactNumber)) ?>/' + id;
	if (action) route += '/' + action;

	xhttp.open('GET', route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>
			document.getElementById('account-update-panel').innerHTML = xhttp.responseText;

			if (id) {
				$('#account-update-anchor').click(function () { get<?php echo $contactNumber ?>Update(id, 'update'); });
				$('#account-delete-anchor').click(function () { get<?php echo $contactNumber ?>Update(id, 'delete'); });
			}
			else $('#account-add-anchor').click(function () { get<?php echo $contactNumber ?>Update(id, 'add'); });

			connect<?php echo $contactNumber ?>UpdateForm(id, action);
<?php if (!$config['isTraceActive']) : ?>
			}
<?php endif;?>
		}
	}
	xhttp.send();

	// Highlight the clicked button (and only it in its class)
/*	$('.action-btn').removeClass("btn-primary").addClass("btn-default");
	if (action == 'update') $('#account-update-anchor').removeClass("btn-default").addClass("btn-primary");
	else if (action == 'delete') $('#account-delete-anchor').removeClass("btn-default").addClass("btn-primary");*/
}

<?php endforeach;?>

// Load the list
function getCommitmentAccountList(params, major, dir) {		

	// Execute the ajax request
	route = '<?php echo $this->url('commitment/accountList', array('type' => $type)) ?>'
	route += params + '&major=' + major + ((dir =='ASC') ? '&dir=ASC' : '&dir=DESC');
	xhttp = new XMLHttpRequest();
	xhttp.open("GET", route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>
			document.getElementById('commitment-list-panel').innerHTML = xhttp.responseText;
			
			$(function () {
			    $('.tip').tooltip({
			        content: function () {
			            return $(this).prop('title');
			        }
			    });
			});
			
			// Connect the add anchors
			$('#commitment-add').click(function () {
				getCommitmentUpdate(0, '', params);
			});
			
			// Connect the detail anchors
			$('.commitment-detail-anchor').each(function () {
				$(this).click(function () {
					getCommitmentUpdate($(this).attr('id').split('_')[1], 'update', params);
				});
			});
			
			// Connect the delete anchors
			$('.commitment-delete-anchor').each(function () {
				$(this).click(function () {
					getCommitmentUpdate($(this).attr('id').split('_')[1], 'delete', params);
				});
			});

			$('.account-list-anchor').each(function () {
				$(this).click(function () {
					document.location.href = $(this).attr('id');
				});
			});
<?php if (!$config['isTraceActive']) : ?>
			}
<?php endif;?>
		}
	}
	xhttp.send();
}

// Load the detail panel
function getAccountDetail(id) {

	// Ensure the target is displayed
	$('#form_action').show();
	$('#iframe_action').hide();

	// Anchor to the new panel
	$(location).attr('hash', 'form_action');

	var route = '<?php echo $this->url('commitmentAccount/detail', array('type' => $type)) ?>' + '/' + id;

	// Execute the ajax request
	xhttp = new XMLHttpRequest();
	xhttp.open("GET", route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>
			document.getElementById('form_action').innerHTML = xhttp.responseText;
			
			connectAuditPanel();
			connectRemoveIcon('remove-anchor', 'form_action');

			getAccountUpdate(id, '');
			$('#contact_1-tab').addClass('active');

<?php foreach (array('contact_1', 'user', 'contact_2', 'contact_3', 'contact_4') as $tabId) : ?>
			$('#<?php echo $tabId ?>-tab').click(function () {
				$('.account-tab').removeClass('active');
				$('#<?php echo $tabId ?>-tab').addClass('active');
	<?php if ($tabId == 'contact_1') : ?>
				getAccountUpdate(id, '');
	<?php elseif ($tabId == 'user') : ?>
				getUserUpdate(id, '');
	<?php else : ?>
				get<?php echo $tabId ?>Update(id, '');
	<?php endif;?>
			});
<?php endforeach;?>

<?php if (array_key_exists('p-pit-engagements', $context->getApplications())) : ?>
			if (id != 0) {
				getCommitmentAccountList('?account_id=' + id, 'identifier', 'DESC');
			}
<?php endif;?>

<?php if (!$config['isTraceActive']) : ?>
			}
<?php endif;?>
		}
	}
	xhttp.send();

	// Highlight the clicked button (and only it in its class)
	$('.index-btn').removeClass("btn-primary").addClass("btn-default");
	$('#account-detail-anchor_' + id).removeClass("btn-default").addClass("btn-primary");
}

// SendMessage

<?php 
$properties = array();
$properties['mask_recipients'] = array('type' => 'checkbox');
$properties['template_id'] = array('type' => 'select', 'mandatory' => true);
foreach ($templates as $templateId => $template) {
	$properties[$templateId.'_subject'] = array('type' => 'input', 'mandatory' => 'true', 'maxSize' => 255);
	$properties[$templateId.'_body'] = array('type' => 'ckeditor', 'mandatory' => 'true', 'maxSize' => 65535);
}
$properties['attachment'] = array('type' => 'select', 'mandatory' => false);
$properties['update_time'] = array('type' => 'hidden');
echo $this->partial('/partials/check-update-properties', array('entity' => 'Mail', 'context' => $context, 'properties' => $properties)) 
?>

function connectSendMessageForm(id)
{
<?php foreach ($properties as $propertyId => $property) : ?>
	<?php if ($property['type'] == 'date') : ?>
		$('#input_<?php echo $propertyId ?>').datepicker();
	<?php elseif ($property['type'] == 'time') : ?>
		$('#<?php echo $propertyId ?>').timepicker({ 'timeFormat': 'H:i:s' });
	<?php endif;?>
<?php endforeach ?>

	var form = document.getElementById('ppit-form');
	
	// Check validity
	var validity = checkMailUpdateProperties(id);

	if (validity) {
		
		// Create a new FormData object.
		var formData = new FormData();
	
		var accountNumber = $('#account-number').val();
		for (i = 0, j = 0; i < accountNumber; i++) {
			if (document.getElementById('account-checkbox_' + i).checked) {
				formData.append('account_' + j, $('#account_' + i).val());
				j++;
			}
		}
		formData.append('nb-account', j);
			
		// Get the properties values
<?php foreach ($properties as $propertyId => $property) : ?>
	<?php if (in_array($property['type'], array('input', 'date', 'time', 'textarea', 'log', 'select', 'repository', 'number', 'email', 'phone', 'hidden'))) : ?>
		formData.append('<?php echo $propertyId ?>', document.getElementById('<?php echo $propertyId ?>').value);

	<?php elseif ($property['type'] == 'checkbox') : ?>
		formData.append('<?php echo $propertyId ?>', ((document.getElementById('<?php echo $propertyId ?>').checked) ? 1 : 0));

	<?php elseif ($property['type'] == 'ckeditor') : ?>
		formData.append('<?php echo $propertyId ?>', CKEDITOR.instances.<?php echo $propertyId ?>.getData());

	<?php endif ?>

<?php endforeach ?>
	
		var xhttp = new XMLHttpRequest();
		var route = '<?php echo $this->url('commitmentAccount/sendMessage') ?>';
	
		// Execute the ajax request
		xhttp = new XMLHttpRequest();
		xhttp.open("POST", route, true);
		xhttp.onreadystatechange = function() {
				if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
			if (xhttp.readyState == 4) {
		<?php if (!$config['isTraceActive']) : ?>
				if (xhttp.status == 200) {
		<?php endif;?>
	
				document.getElementById('send-message-panel').innerHTML = xhttp.responseText;
				showTemplate();
				
				$(function () {
				    $('.tip').tooltip({
				        content: function () {
				            return $(this).prop('title');
				        }
				    });
				});
				
				connectRemoveIcon('remove-anchor', 'form_action');
		<?php if (!$config['isTraceActive']) : ?>
				}
		<?php endif;?>
			}
		}
		xhttp.send(formData);
	}
	else return false;
}

function getSendMessageForm() {
	$('#send-message-button').removeClass('btn-default').addClass('btn-warning');
	$('#send-message-alert').show();
	$('#send-message-button').click(function () { connectSendMessageForm(); });
}

function showTemplate() {
	templateId = $('#template_id').val();
	$('.email-template').hide();
	$('#email-template_' + templateId).show();
}

function getSendMessage() {

	var xhttp = new XMLHttpRequest();
	var route = '<?php echo $this->url('commitmentAccount/sendMessage') ?>';

	// Execute the ajax request
	xhttp = new XMLHttpRequest();
	xhttp.open("GET", route, true);
	xhttp.onreadystatechange = function() {
			if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>

			document.getElementById('send-message-panel').innerHTML = xhttp.responseText;
<?php foreach ($properties as $propertyId => $property) : ?>
	<?php if ($property['type'] == 'ckeditor') : ?>
			CKEDITOR.replace('<?php echo $propertyId ?>');
	<?php endif;?>
<?php endforeach;?>
			
			$(function () {
			    $('.tip').tooltip({
			        content: function () {
			            return $(this).prop('title');
			        }
			    });
			});

			connectRemoveIcon('remove-anchor', 'form_action');
			showTemplate();
			$('#template_id').change(showTemplate);
			$('#attachment').change(function () {
				if ($('#attachment').val()) $('#attachment_link').html('<a class="glyphicon glyphicon-paperclip" href="<?php echo $this->url('commitmentAccount/dropboxLink', array(), array('force_canonical' => true)) ?>/' + $('#attachment').val() + '" target="_blank"></a>'); 
				else $('#attachment_link').html('');
			});
			$('#send-message-alert').hide();
			$('#send-message-button').click(function () { getSendMessageForm(); });
			
	<?php if (!$config['isTraceActive']) : ?>
			}
	<?php endif;?>
		}
	}
	xhttp.send();
}

// Request password


// SendMessage

function connectPasswordRequestForm()
{
	var form = document.getElementById('ppit-form');
	var formData = new FormData();
	var accountNumber = $('#account-number').val();
	for (i = 0, j = 0; i < accountNumber; i++) {
		if (document.getElementById('account-checkbox_' + i).checked) {
			formData.append('account_' + j, $('#account_' + i).val());
			j++;
		}
	}
	formData.append('nb-account', j);

	var xhttp = new XMLHttpRequest();
	var route = '<?php echo $this->url('commitmentAccount/passwordRequest') ?>';

	// Execute the ajax request
	xhttp = new XMLHttpRequest();
	xhttp.open("POST", route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
			document.getElementById('password-request-panel').innerHTML = xhttp.responseText;
		}
	}
	xhttp.send(formData);
}

function getRequestPasswordForm() {
	$('#password-request-button').removeClass('btn-default').addClass('btn-warning');
	$('#password-request-alert').show();
	$('#password-request-button').click(function () { connectPasswordRequestForm(); });
}

function getPasswordRequest() {

	var xhttp = new XMLHttpRequest();
	var route = '<?php echo $this->url('commitmentAccount/passwordRequest') ?>';

	// Execute the ajax request
	xhttp = new XMLHttpRequest();
	xhttp.open("GET", route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
			document.getElementById('password-request-panel').innerHTML = xhttp.responseText;
			$('#password-request-alert').hide();
			$('#password-request-button').click(function () { getRequestPasswordForm(); });
			
		}
	}
	xhttp.send();
}


// Grouped actions

<?php 
$properties = array();

foreach ($context->getConfig('commitmentAccount/groupUpdate'.(($type) ? '/'.$type : '')) as $propertyId => $options) {
	$property = $context->getConfig('commitmentAccount'.(($type) ? '/'.$type : ''))['properties'][$propertyId];
	if ($propertyId != 'place_id' && $property['type'] == 'repository') $property = $context->getConfig($property['definition']);
	if ($options && (!array_key_exists('readonly', $options) || !$options['readonly']) && $property['type'] != 'title') {
		$properties[$propertyId] = array('type' => $property['type'], 'mandatory' => $options['mandatory'], 'maxSize' => ($property['type'] == 'textarea' || $property['type'] == 'log') ? 2047 : 255);
	}
}

$properties['update_time'] = array('type' => 'hidden');

echo $this->partial('/partials/check-update-properties', array('entity' => 'Group', 'context' => $context, 'properties' => $properties)) 
?>

function postGroup()
{

<?php foreach ($properties as $propertyId => $property) : ?>
	<?php if ($property['type'] == 'date') : ?>
		$('#input_<?php echo $propertyId ?>').datepicker();
	<?php elseif ($property['type'] == 'time') : ?>
		$('#<?php echo $propertyId ?>').timepicker({ 'timeFormat': 'H:i:s' });
	<?php endif;?>
<?php endforeach ?>

	var form = document.getElementById('group-form');
	form.onsubmit = function(event) {
		event.preventDefault();
	
		// Check validity
		var validity;
		validity = checkGroupUpdateProperties();

		if (validity) {
		
			// Create a new FormData object.
			var formData = new FormData();
			formData.append('action', 'update');
			var nbAccount = $('#group-nb-account').val();
			formData.append('nb-account', nbAccount);
			for (i = 0; i < nbAccount; i++) formData.append('account_' + i, $('#group-account_' + i).val());
			
			// Get the properties values
<?php foreach ($properties as $propertyId => $property) : ?>
	<?php if (in_array($property['type'], array('input', 'date', 'time', 'textarea', 'log', 'select', 'repository', 'number', 'email', 'phone', 'hidden'))) : ?>
			formData.append('<?php echo $propertyId ?>', document.getElementById('<?php echo $propertyId ?>').value);

	<?php elseif ($property['type'] == 'checkbox') : ?>
			formData.append('<?php echo $propertyId ?>', ((document.getElementById('<?php echo $propertyId ?>').checked) ? 1 : 0));

	<?php endif ?>

<?php endforeach ?>

			var xhttp = new XMLHttpRequest();
			var route, target;
			route = '<?php echo $this->url('commitmentAccount/group', array('type' => $type)) ?>';
			target = 'form_action';
			xhttp.open('POST', route, true);
			xhttp.onload = function () {
				if (xhttp.readyState == 4 <?php if (!$context->getConfig()['isTraceActive']) echo '&& xhttp.status == 200' ?>) {
					document.getElementById(target).innerHTML = xhttp.responseText;
					filterAccountList();
					postGroup();
				}
				connectRemoveIcon('remove-anchor', 'form_action');
			};
			xhttp.send(formData);
		}
		else return false;
	}
}

function getAccountGroup() {

	// Ensure the target is displayed
	$('#form_action').show();
	$(location).attr('hash', 'form_action');

	// Disabled the list checkboxes
	$('.account-checkbox').attr('disabled', 'disabled');
	var route = '<?php echo $this->url('commitmentAccount/group', array('type' => $type)) ?>';
	var formData = new FormData();

	var accountNumber = $('#account-number').val();
	for (i = 0, j = 0; i < accountNumber; i++) {
		if (document.getElementById('account-checkbox_' + i).checked) {
			formData.append('account_' + j, $('#account_' + i).val());
			j++;
		}
	}
	formData.append('nb-account', j);

	// Execute the ajax request
	xhttp = new XMLHttpRequest();
	xhttp.open("POST", route, true);
	xhttp.onreadystatechange = function() {
			if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
		if (xhttp.readyState == 4) {
	<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
	<?php endif;?>

			document.getElementById('form_action').innerHTML = xhttp.responseText;
			postGroup();
			getSendMessage(false);
			
<?php if ($context->hasRole('admin')) : ?>
			getPasswordRequest(false);
<?php endif;?>

			$(function () {
			    $('.tip').tooltip({
			        content: function () {
			            return $(this).prop('title');
			        }
			    });
			});
			
			connectRemoveIcon('remove-anchor', 'form_action');
	<?php if (!$config['isTraceActive']) : ?>
			}
	<?php endif;?>
		}
	}
	xhttp.send(formData);

	// Highlight the clicked button (and only it in its class)
	$('.index-btn').removeClass("btn-primary").addClass("btn-default");
	$('.account-group-anchor').removeClass("btn-default").addClass("btn-primary");
}

function activateAccount() {

	// Load the search panel and highlight the menu entry
	loadPanel('index_action', '<?php echo $this->url('commitmentAccount/search', array('entry' => $entry, 'type' => $type)) ?>?');

	<?php
	$todoTitle = (isset ($context->getConfig('commitmentAccount/search'.(($type) ? '/'.$type : ''))['todoTitle']) ? $context->getConfig('commitmentAccount/search'.(($type) ? '/'.$type : ''))['todoTitle'][$context->getLocale()] : $this->translate('active', 'ppit-core', $context->getLocale()));
	?>
	$('#mode-text').text('<?php echo $todoTitle ?>');
		
	// Connect the search inputs
	connectAccountSearchInputs();
	
	getAccountList('?', '<?php echo $context->getConfig('commitmentAccount'.(($type) ? '/'.$type : ''))['order'] ?>', 'ASC');
	
	$('#add-criteria').click(function () {
		mode = $('#add-criteria').text();
		if (mode == '<?php echo $this->translate('More criteria', 'ppit-core', $context->getLocale()) ?>') {
			$('#add-criteria').text('<?php echo $this->translate('Less criteria', 'ppit-core', $context->getLocale()) ?>');
			$('#search-area').show();
		}
		else {
			$('#add-criteria').text('<?php echo $this->translate('More criteria', 'ppit-core', $context->getLocale()) ?>');
			$('#search-area').hide();
		}
	});
	$('#search-area').hide();
}

/////////////////////////////
// Commitment update panel //
/////////////////////////////

<?php
$properties = array();

$properties['commitment-type'] = array('type' => 'select', 'mandatory' => 'true', 'maxSize' => 255);
foreach ($context->getConfig('commitment/update'.(($type) ? '/'.$type : '')) as $propertyId => $options) {
	$property = $context->getConfig('commitment'.(($type) ? '/'.$type : ''))['properties'][$propertyId];
	$properties['commitment-'.$propertyId] = array('type' => $property['type'], 'mandatory' => $options['mandatory'], 'maxSize' => ($property['type'] == 'textarea' || $property['type'] == 'log') ? 2047 : 255);
}

$properties['update_time'] = array('type' => 'hidden');

echo $this->partial('/partials/check-update-properties', array('entity' => 'Commitment', 'context' => $context, 'properties' => $properties)) 
?>

function connectCommitmentUpdateForm(id, action, params)
{

	if (action == 'update') $('#commitment-update-anchor').removeClass('btn-default').addClass('btn-primary');
	if (action == 'delete') $('#commitment-delete-anchor').removeClass('btn-default').addClass('btn-primary');

<?php foreach ($properties as $property_id => $property) : ?>
	<?php if ($property['type'] == 'date') : ?>
		$('#input_<?php echo $property_id ?>').datepicker();
	<?php elseif ($property['type'] == 'time') : ?>
		$('#<?php echo $propertyId ?>').timepicker({ 'timeFormat': 'H:i:s' });
	<?php endif;?>
<?php endforeach ?>

	var form = document.getElementById('commitment-form');
	form.onsubmit = function(event) {
		
		event.preventDefault();
	
		// Check validity
		var validity = checkCommitmentUpdateProperties(id);
		if (validity) {
		
			// Create a new FormData object.
			var formData = new FormData();
			
			// Get the properties values
<?php foreach ($properties as $propertyId => $property) : ?>

	<?php if (in_array($property['type'], array('input', 'date', 'time', 'textarea', 'log', 'select', 'repository', 'number', 'email', 'phone', 'hidden'))) : ?>
				formData.append('<?php echo $propertyId ?>', document.getElementById('<?php echo $propertyId ?>').value);

	<?php elseif ($property['type'] == 'checkbox') : ?>
				formData.append('<?php echo $propertyId ?>', ((document.getElementById('<?php echo $propertyId ?>').checked) ? 1 : 0));

	<?php elseif ($property['type'] == 'file') : ?>
				var fileSelect = document.getElementById('order_form');
				if (fileSelect) {
					var files = fileSelect.files;
					for (var i = 0; i < files.length; i++) {
						var file = files[i];
						formData.append('order_form', file, file.name);
					}
				}

	<?php endif ?>

<?php endforeach ?>

			var xhttp = new XMLHttpRequest();
			var route, target;
			route = '<?php echo $this->url('commitment/update', array('type' => ($type) ? $type : 'generic')) ?>/' + id;
			if (action) route += '/' + action;
			route += params;
			target = 'commitment-update-panel';
			xhttp.open('POST', route, true);
			// Set up a handler for when the request finishes.
			xhttp.onload = function () {
				if (xhttp.readyState == 4 <?php if (!$context->getConfig()['isTraceActive']) echo '&& xhttp.status == 200' ?>) {

<?php if ($context->getConfig()['isTraceActive']) : ?>
					console.log('post, route = ' + route);
					console.log(xhttp.responseText);
<?php endif;?>
					document.getElementById(target).innerHTML = xhttp.responseText;
				}
			};
			xhttp.send(formData);
		}
		else return false;
	}
}

function getCommitmentUpdate(id, action, params) {

	var xhttp = new XMLHttpRequest();
	var route = '<?php echo $this->url('commitment/update', array('type' => ($type) ? $type : 'generic')) ?>/' + id;
	if (action) route += '/' + action;
	route += params;
	xhttp.open('GET', route, true);
	xhttp.onreadystatechange = function() {
		if (xhttp.readyState == 4) {
<?php if (!$config['isTraceActive']) : ?>
			if (xhttp.status == 200) {
<?php endif;?>
			document.getElementById('commitment-update-panel').innerHTML = xhttp.responseText;
			
			$(function () {
			    $('.tip').tooltip({
			        content: function () {
			            return $(this).prop('title');
			        }
			    });
			});

			if (id) {
				$('#commitment-update-anchor').click(function () { getCommitmentUpdate(id, 'update'); });
				$('#commitment-delete-anchor').click(function () { getCommitmentUpdate(id, 'delete'); });
			}
			else $('#commitment-add-anchor').click(function () { getCommitmentUpdate(id, 'add'); });
			
			connectCommitmentUpdateForm(id, action, params);
<?php if (!$config['isTraceActive']) : ?>
			}
<?php endif;?>
		}
	}
	xhttp.send();
}