<div class="panel panel-default">
	<div class="panel-heading" style="background:  <?php echo $context->getConfig('styleSheet')['panelHeadingBackground'] ?>; color: <?php echo $context->getConfig('styleSheet')['panelHeadingColor'] ?>">
		<strong><?php echo ($account->id) ? $account->customer_name : $this->translate('Add', 'ppit-core', $context->getLocale()) ?></strong>
 		<div class="btn-group pull-right">
			<button type="button" class="btn btn-default" title="<?php echo $this->translate('Return to list', 'ppit-core', $context->getLocale()) ?>" id="remove-anchor">
				<span class="glyphicon glyphicon-remove"></span>
			</button>
 		 </div>
	</div>
	<div class="panel-body">

<?php if ($context->hasRole('admin') && $account->id) : ?>
<!-- Display the audit -->
		<?php echo $this->translate('History', 'ppit-core', $context->getLocale()) ?> (<a id="audit-label" href="#"><?php echo $this->translate('Show', 'ppit-core', $context->getLocale()) ?></a>)
		<div id="audit-panel" class="panel panel-default">
			<div class="panel-body">
	<?php foreach ($account->audit as $comment) : ?>
				<div class="row">
					<div class="col-md-12">
						<strong><?php echo $context->decodeDate(substr($comment['time'], 0, 10)).substr($comment['time'], 10) ?>:</strong>&nbsp;
						<?php if (array_key_exists('status', $comment)) echo $context->getconfig('commitmentAccount'.(($type) ? '/'.$type : ''))['statuses'][$comment['status']]['labels'][$context->getLocale()] ?>&nbsp;
						(<?php echo $comment['n_fn'] ?>)
					</div>
				</div>
				<div class="row">
					<div class="col-md-2" align="right">&nbsp;</div>
					<div class="col-md-10"><em><?php echo $comment['comment'] ?></em></div>
				</div>
	<?php endforeach;?>
			</div>
		</div>
		<div>&nbsp;</div>
		<div>
<?php endif;?>
				
<?php if ($account->id) : ?>
		<ul class="nav nav-tabs">
	<?php $first=true; foreach ($context->getConfig('commitmentAccount/detail'.(($type) ? '/'.$type : ''))['tabs'] as $tabId => $tab) : ?>
		  <li data-toggle="tab" class="account-tab <?php if ($first) echo 'active' ?>"><a id="<?php echo $tabId ?>-tab"><?php echo $tab['labels'][$context->getLocale()] ?></a></li>
	<?php $first=false; endforeach;?>
		</ul>
<?php endif;?>

		<div class="tab-content">
			<div class="tab-pane fade in active" id="account-update-panel"></div>
		</div>

		<div id="commitment-list-panel"></div>
	</div>
	