<table class="table table-striped ppit_index">
	<tr>
		<th>&nbsp;</th>

<?php $first = true; foreach ($context->getConfig('commitmentAccount/list'.(($type) ? '/'.$type : '')) as $propertyId => $rendering) : ?>
		<th align="center">
	<?php $label = $context->getConfig('commitmentAccount'.(($type) ? '/'.$type : ''))['properties'][$propertyId]['labels'][$context->getLocale()] ?>
	<?php if ($label) : ?>
			<button type="button" class="btn btn-default btn-xs ppit-sort-anchor" id="<?php echo $propertyId ?>-anchor">
				<span><?php echo $label ?></span>
<?php if ($major == $propertyId) : ?>
				<span class="glyphicon glyphicon-triangle-<?php echo ($dir == 'ASC') ? 'top' : 'bottom' ?>"></span>
<?php endif ?>
			</button>
		<?php if ($first && $context->isDemoModeActive()) : ?>
			<a class="tip" href="#" title="<?php echo $context->getConfig('demo')['commitmentAccount/list/ordering'][$context->getLocale()] ?>">
			    <img src="<?php echo $this->basePath('img/tip.png') ?>" width="20" />
			</a>
		<?php $first=false; endif;?>
	<?php endif;?>
		</th>
<?php endforeach;?>

	<tr>
		<td style="text-align: center">
			<button type="button" class="btn btn-default index-btn account-detail-anchor" title="<?php echo $this->translate('Add', 'ppit-core', $context->getLocale())?>" id="account-detail-anchor_0">
				<span class="glyphicon glyphicon-plus" id="add-glyphicon"></span>
			</button>
<?php if ($context->isDemoModeActive()) : ?>
	<?php
	if ($entry == 'contact') $qualifier = 'commitmentAccount/list/contact/add';
	else $qualifier = 'commitmentAccount/list'.(($type) ? '/'.$type : '').'/add';
	?>
			<a class="tip" href="#" title="<?php echo $context->getConfig('demo')[$qualifier][$context->getLocale()] ?>">
			    <img src="<?php echo $this->basePath('img/tip.png') ?>" width="20" />
			</a>
<?php endif;?>
		</td>
		
		<td colspan="6">
<?php if ($entry == 'contact') : ?>
			<button type="button" class="btn btn-default index-btn" title="<?php echo $this->translate('Register form', 'ppit-commitment', $context->getLocale())?>" id="account-register-anchor">
				<?php echo $this->translate('Register form', 'ppit-commitment', $context->getLocale()) ?>
			</button>
<?php endif;?>
		</td>
	</tr>

<?php $i = 0; foreach ($accounts as $account) : ?>
	<?php 
	$color = null;
	if ($account->status == 'new') $backgroundColor = 'LightGreen';
	elseif ($account->status == 'warm') $backgroundColor = 'LightSalmon';
	elseif ($account->status == 'cold') { $backgroundColor = 'Red'; $color = 'white'; }
	else $backgroundColor = null;
	?>
	
	<tr class="account">
	
		<td style="text-align: center">
			<button type="button" class="btn btn-default index-btn account-detail-anchor" title="<?php echo $this->translate('Detail', 'ppit-core', $context->getLocale())?>" id="account-detail-anchor_<?php echo $account->id ?>">
				<span class="glyphicon glyphicon-zoom-in" id="<?php echo $account->id ?>-glyphicon"></span>
			</button>
<?php if ($i == 0 && $context->isDemoModeActive()) : ?>
	<?php
	if ($entry == 'contact') $qualifier = 'commitmentAccount/list/contact/detail';
	else $qualifier = 'commitmentAccount/list'.(($type) ? '/'.$type : '').'/detail';
	?>
			<a class="tip" href="#" title="<?php echo $context->getConfig('demo')[$qualifier][$context->getLocale()] ?>">
			    <img src="<?php echo $this->basePath('img/tip.png') ?>" width="20" />
			</a>
<?php endif;?>
		</td>

	<?php foreach ($context->getConfig('commitmentAccount/list'.(($type) ? '/'.$type : '')) as $propertyId => $rendering) : ?>
	
		<?php if ($propertyId == 'customer_name') : ?>
		<td style=" <?php if ($backgroundColor) echo 'font-weight: bold; background-color: '.$backgroundColor.';' ?> <?php if ($color) echo 'color: '.$color.';' ?>"><?php echo $account->customer_name ?></td>
	
		<?php elseif ($propertyId == 'n_fn') : ?>
		<td style="<?php if ($backgroundColor) echo 'font-weight: bold; background-color: '.$backgroundColor.';' ?> <?php if ($color) echo 'color: '.$color.';' ?>"><?php echo $account->n_fn ?></td>
	
		<?php elseif ($rendering == 'text') : ?>
		<td><?php echo $account->properties[$propertyId] ?></td>
	
		<?php elseif ($rendering == 'photo') : ?>
		<td>
			<span class="info">
				<img height="40" src="<?php echo $this->basePath('photos/'.(($account->photo_link_id) ? $account->photo_link_id :  $account->contact_1_id.'.jpg')) ?>"/>
				<span><img height="150" src="<?php echo $this->basePath('photos/'.(($account->photo_link_id) ? $account->photo_link_id :  $account->contact_1_id.'.jpg')) ?>"/></span>
			</span>
		</td>

		<?php elseif ($rendering == 'image') : ?>
		<td style="text-align: center">
			<img height="20" src="<?php echo $this->basePath('/img'.(($type) ? '/'.$type : '').'/'.$account->properties[$propertyId].'.png') ?>" title="<?php echo $account->properties[$propertyId] ?>" alt="<?php echo $account->properties[$propertyId] ?>" /><br>
		</td>

		<?php elseif ($rendering == 'phone') : ?>
		<td>
			<a href="tel:<?php echo $account->properties[$propertyId] ?>"><?php echo $account->properties[$propertyId] ?></a>
		</td>
	
		<?php else : ?>
		<td><?php echo $account->properties[$propertyId] ?></td>
		
		<?php endif;?>
		
	<?php endforeach;?>
	</tr>
	
<?php $i++; endforeach; ?>

</table>
