<table class="table table-striped ppit_index">
	<tr>
		<th>&nbsp;</th>
		<th>&nbsp;</th>

<?php $first = true; foreach ($context->getConfig('commitmentAccount/list'.(($type) ? '/'.$type : '')) as $propertyId => $rendering) : ?>
	<?php 
	$property = $context->getConfig('commitmentAccount'.(($type) ? '/'.$type : ''))['properties'][$propertyId];
	if ($property['type'] == 'repository') $property = $context->getConfig($property['definition']);
	?>

		<th align="center">
	<?php $label = $property['labels'][$context->getLocale()] ?>
	<?php if ($label) : ?>
			<button type="button" class="btn btn-default btn-xs ppit-sort-anchor" id="<?php echo $propertyId ?>-anchor">
				<span><?php echo $label ?></span>
<?php if ($major == $propertyId) : ?>
				<span class="glyphicon glyphicon-triangle-<?php echo ($dir == 'ASC') ? 'top' : 'bottom' ?>"></span>
<?php endif ?>
			</button>
		<?php if ($first && $context->isDemoModeActive()) : ?>
			<a class="tip" href="#" title="<?php echo $context->getConfig('demo')['commitmentAccount/list/ordering'][$context->getLocale()] ?>">
			    <img src="<?php echo $this->basePath('img/tip.png') ?>" width="20" />
			</a>
		<?php $first=false; endif;?>
	<?php endif;?>
		</th>
<?php endforeach;?>

	<tr>
		<td>
			<input type="checkbox" class="account-checkbox" id="account-checkbox" title="<?php echo $this->translate('Check all', 'ppit-core', $context->getLocale()) ?>"></input>
<?php if ($context->isDemoModeActive()) : ?>
			<br>
			<a class="tip" href="#" title="<?php echo $context->getConfig('demo')['commitmentAccount/list/checkAll'][$context->getLocale()] ?>">
			    <img src="<?php echo $this->basePath('img/tip.png') ?>" width="20" />
			</a>
			<br>
<?php endif;?>
		</td>

		<td style="text-align: center">
			<button type="button" class="btn btn-default index-btn account-group-anchor" title="<?php echo $this->translate('Grouped actions', 'ppit-core', $context->getLocale())?>" id="account-group-anchor" disabled="disabled">
				<span class="glyphicon glyphicon-list-alt" id="group-glyphicon"></span>
			</button>
<?php if ($context->isDemoModeActive()) : ?>
				<br>
				<a class="tip" href="#" title="<?php echo $context->getConfig('demo')['commitmentAccount/list/groupedActions'][$context->getLocale()] ?>">
				    <img src="<?php echo $this->basePath('img/tip.png') ?>" width="20" />
				</a>
<?php endif;?>
		</td>
		
		<td style="text-align: center">
			<button type="button" class="btn btn-default index-btn account-detail-anchor" title="<?php echo $this->translate('Add', 'ppit-core', $context->getLocale())?>" id="account-detail-anchor_0">
				<span class="glyphicon glyphicon-plus" id="add-glyphicon"></span>
			</button>
<?php if ($context->isDemoModeActive()) : ?>
			<a class="tip" href="#" title="<?php echo $context->getConfig('demo')['commitmentAccount/list'.(($type) ? '/'.$type : '').'/add'][$context->getLocale()] ?>">
			    <img src="<?php echo $this->basePath('img/tip.png') ?>" width="20" />
			</a>
<?php endif;?>
		</td>
		
		<td colspan="5">&nbsp;</td>
	</tr>

	<input type="hidden" id="account-number" value="<?php echo count($accounts) ?>" />

<?php $i = 0; foreach ($accounts as $account) : ?>
	
	<input type="hidden"  id="account_<?php echo $i ?>" value="<?php echo $account->id ?>" />

	<?php 
	$color = null;
	if ($account->status == 'new') $backgroundColor = 'LightGreen';
	elseif (!in_array($account->status, array('new', 'active', 'gone'))) $backgroundColor = 'LightSalmon';
	elseif ($account->status == 'gone') { $backgroundColor = 'Red'; $color = 'white'; }
	else $backgroundColor = null;
	?>
	
	<tr class="account">
		<td>
			<input type="checkbox" class="account-checkbox" id="account-checkbox_<?php echo $i ?>"></input>
		</td>
	
		<td style="text-align: center">
			<button type="button" class="btn btn-default index-btn account-detail-anchor" title="<?php echo $this->translate('Detail', 'ppit-core', $context->getLocale())?>" id="account-detail-anchor_<?php echo $account->id ?>">
				<span class="glyphicon glyphicon-zoom-in" id="<?php echo $account->id ?>-glyphicon"></span>
			</button>
<?php if ($i == 0 && $context->isDemoModeActive()) : ?>
			<a class="tip" href="#" title="<?php echo $context->getConfig('demo')['commitmentAccount/list'.(($type) ? '/'.$type : '').'/detail'][$context->getLocale()] ?>">
			    <img src="<?php echo $this->basePath('img/tip.png') ?>" width="20" />
			</a>
<?php endif;?>
		</td>

	<?php foreach ($context->getConfig('commitmentAccount/list'.(($type) ? '/'.$type : '')) as $propertyId => $rendering) : ?>
		<?php 
		$property = $context->getConfig('commitmentAccount'.(($type) ? '/'.$type : ''))['properties'][$propertyId];
		if ($property['type'] == 'repository') $property = $context->getConfig($property['definition']);
		?>
	
		<?php if ($propertyId == 'name') : ?>
		<td style=" <?php if ($backgroundColor) echo 'font-weight: bold; background-color: '.$backgroundColor.';' ?> <?php if ($color) echo 'color: '.$color.';' ?>"><?php echo $account->name ?></td>
	
		<?php elseif ($propertyId == 'n_fn') : ?>
		<td style="<?php if ($backgroundColor) echo 'font-weight: bold; background-color: '.$backgroundColor.';' ?> <?php if ($color) echo 'color: '.$color.';' ?>"><?php echo $account->n_fn ?></td>
	
		<?php elseif ($rendering == 'text') : ?>
		<td><?php echo $account->properties[$propertyId] ?></td>
	
		<?php elseif ($rendering == 'select') : ?>
		<td><?php echo $property['modalities'][$account->properties[$propertyId]][$context->getLocale()] ?></td>
	
		<?php elseif ($rendering == 'date') : ?>
		<td><?php echo $context->decodeDate($account->properties[$propertyId]) ?></td>
	
		<?php elseif ($rendering == 'photo') : ?>
		<td>
			<span class="info">
				<img height="40" src="<?php echo $this->basePath('photos/'.(($account->photo_link_id) ? $account->photo_link_id :  $account->contact_1_id.'.jpg')) ?>"/>
				<span><img height="150" src="<?php echo $this->basePath('photos/'.(($account->photo_link_id) ? $account->photo_link_id :  $account->contact_1_id.'.jpg')) ?>"/></span>
			</span>
		</td>

		<?php elseif ($rendering == 'image') : ?>
		<td style="text-align: center">
			<?php $label = (array_key_exists($account->properties[$propertyId], $property['modalities'])) ? $property['modalities'][$account->properties[$propertyId]][$context->getLocale()] : $account->properties[$propertyId] ?>
			<img height="20" src="<?php echo $this->basePath('/img'.(($type) ? '/'.$type : '').'/'.$account->properties[$propertyId].'.png') ?>" title="<?php echo $label ?>" alt="<?php echo $label ?>" /><br>
		</td>

		<?php elseif ($rendering == 'phone') : ?>
		<td>
			<a href="tel:<?php echo $account->properties[$propertyId] ?>"><?php echo $account->properties[$propertyId] ?></a>
		</td>
	
		<?php else : ?>
		<td><?php echo $account->properties[$propertyId] ?></td>
		
		<?php endif;?>
		
	<?php endforeach;?>
	</tr>
	
<?php $i++; endforeach; ?>

	<tr>
		<td>
			<input type="checkbox" class="account-checkbox" id="down-account-checkbox"></input>
		</td>

		<td style="text-align: center">
			<button type="button" class="btn btn-default index-btn account-group-anchor" title="<?php echo $this->translate('Grouped actions', 'ppit-core', $context->getLocale())?>" id="account-down-group-anchor" disabled="disabled">
				<span class="glyphicon glyphicon-list-alt" id="down-group-glyphicon"></span>
			</button>
		</td>

<?php if ($mode == 'todo' && count($accounts) == '50') : ?>
		<td style="text-align: center">
			<button type="button" class="btn btn-default index-btn" title="<?php echo $this->translate('Display the entire list', 'ppit-core', $context->getLocale())?>" id="account-more-anchor">
				<span class="glyphicon glyphicon-option-horizontal" id="more-glyphicon"></span>
			</button>
		</td>
		<td colspan="5">&nbsp;</td>
<?php else : ?>
		<td colspan="6">&nbsp;</td>
<?php endif;?>
	</tr>

</table>
