<!-- 
/**
 * PpitCore V1.0 (https://github.com/p-pit/PpitCore)
 *
 * @link      https://github.com/p-pit/PpitCore
 * @copyright Copyright (c) 2016 Bruno Lartillot
 * @license   https://github.com/p-pit/PpitCore/blob/master/license.txt GNU-GPL license
 */
-->

<hr>
<h4 style="text-align: center">
	<strong><?php echo $this->translate('Password request', 'ppit-core', $context->getLocale()) ?></strong>
</h4>
<form action="" id="password-request-form" method="post" class="form-horizontal" enctype="multipart/form-data">
			
<!-- Global message -->
<?php if ($message == 'OK') : ?>
	<div id="message">
		<div class="alert alert-success"><h4><?php echo $this->translate('Your request has been registered', 'ppit-core', $context->getLocale()) ?></h4></div>
	</div>
<?php endif;?>

<!--  CSRF -->
<?php $element = $csrfForm->get('csrf') ?>
    <div class="form-group">
		<?php echo $this->formElement($element) ?>
<?php if ($this->formElementErrors($element)) : ?>
		<div class="alert alert-danger" style="text-align: center">
			<strong><?php echo $this->translate('The form has expired, please input again', 'ppit-core', $context->getLocale()) ?></strong>
		</div>
<?php endif;?>
	</div>

<?php 
if ($message == 'OK') $isDisabled = true; else $isDisabled = false;
?>
	<div class="panel-body">
		<input type="hidden" id="request_update_time" />

		<div id="message">
			<div class="alert alert-warning">
				<?php echo $this->translate('An email will be sent to the user, allowing her to define a new password.', 'ppit-core', $context->getLocale()) ?><br>
				<strong><?php echo sprintf($this->translate('Please note that this email has a validity of %s days.', 'ppit-core', $context->getLocale()), $context->getConfig()['ppitUserSettings']['tokenValidity']) ?></strong>
			</div>
		</div>

<?php if ($message != 'OK') : ?>
	    <div class="form-group">
			<div class="col-sm-5">&nbsp;</div>
			<div class="col-sm-7">
				<input id="password-request-button" class="btn btn-default" value="<?php echo $this->translate('Send', 'ppit-core', $context->getLocale()) ?>">
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-12">
				<div class="alert alert-warning" id="password-request-alert" style="text-align: center">
					<strong><?php echo $this->translate('Please confirm', 'ppit-core', $context->getLocale()) ?></strong>
				</div>
			</div>
		</div>
<?php endif;?>
	</div>
</form