<div class="panel panel-default">
	<div class="panel-heading" style="background:  <?php echo $context->getConfig('styleSheet')['panelHeadingBackground'] ?>; color: <?php echo $context->getConfig('styleSheet')['panelHeadingColor'] ?>">
		<strong><?php echo $this->translate('Register', 'ppit-commitment', $context->getLocale()) ?></strong>
 		<div class="btn-group pull-right">
			<button type="button" class="btn btn-default" title="<?php echo $this->translate('Return to list', 'ppit-core', $context->getLocale()) ?>" id="remove-anchor">
				<span class="glyphicon glyphicon-remove"></span>
			</button>
 		 </div>
	</div>
	<div class="panel-body">

<!-- Form header -->
<?php echo $this->partial('/partials/form-header', array(
		'update_time' => $account->update_time,
		'message' => $message,
		'error' => $error,
		'csrfForm' => $csrfForm,
		'context' => $context,
));
?>
	
<?php if ($message == 'OK') : ?>
		<p><?php echo $this->translate('An email including a validation link has be sent to you. Please, click on this link.', 'ppit-commitment', $context->getLocale()) ?>
<?php else : ?>
		<h4><?php echo $this->translate('Before starting the trial, we have to know you', 'ppit-commitment', $context->getLocale()) ?></h4>
<?php endif;?>

<?php 
if ($message == 'OK') $isDisabled = true; else $isDisabled = false;
?>

<?php foreach ($context->getConfig('commitmentAccount/register'.(($type) ? '/'.$type : '')) as $propertyId => $options) : ?>
	<?php $property = $context->getConfig('commitmentAccount'.(($type) ? '/'.$type : ''))['properties'][$propertyId] ?>
		<div class="form-group" id="<?php echo (($property['type'] == 'date' || $property['type'] == 'number') ? 'input_' : '').$propertyId ?>_group">
			<label class="col-sm-5 control-label"><?php if ($options['mandatory']) echo '* ' ?><?php echo $property['labels'][$context->getLocale()] ?></label>
			<div class="col-sm-7">

	<?php if ($propertyId == 'name') : ?>
				<input class="form-control" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" value="<?php echo $account->name ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />

	<?php elseif ($propertyId == 'n_first') : ?>
				<input class="form-control" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" value="<?php echo $account->n_first ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
			
	<?php elseif ($propertyId == 'n_last') : ?>
				<input class="form-control" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" value="<?php echo $account->n_last ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
			
	<?php elseif ($propertyId == 'email') : ?>
				<input class="form-control" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" value="<?php echo $account->email ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
			
	<?php elseif ($propertyId == 'tel_work') : ?>
				<input class="form-control" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" value="<?php echo $account->tel_work ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
			
	<?php elseif ($propertyId == 'tel_cell') : ?>
				<input class="form-control" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" value="<?php echo $account->tel_cell ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
				
	<?php elseif ($property['type'] == 'date') : ?>
				<input type="hidden" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" />
				<input class="form-control" id="input_<?php echo $propertyId ?>" name="input_<?php echo $propertyId ?>" value="<?php echo $context->decodeDate($account->properties[$propertyId]) ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />

	<?php elseif ($property['type'] == 'number') : ?>
				<input type="hidden" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" />
				<input class="form-control" id="input_<?php echo $propertyId ?>" name="input_<?php echo $propertyId ?>" value="<?php echo $context->formatFloat($account->properties[$propertyId], 2) ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />

	<?php elseif ($property['type'] == 'textarea') : ?>
				<textarea class="form-control" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?> <?php if ($isDisabled) echo 'disabled="disabled"'?>>
					<?php echo $account->properties[$propertyId] ?>
				</textarea>>

	<?php elseif ($property['type'] == 'select') : ?>
				<select class="form-control" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?>>
	    			<option value=""><-- <?php echo $this->translate('Please select a value', 'ppit-core', $context->getLocale()) ?> --></option>
		<?php foreach ($property['modalities'] as $key => $labels) : ?>
	    			<option value="<?php echo $key ?>" <?php if ($account->properties[$propertyId] == $key) echo 'selected="selected"' ?>><?php echo $labels[$context->getLocale()] ?></option>
		<?php endforeach;?>
				</select>

	<?php elseif ($property['type'] == 'photo') : ?>

<!-- Photo -->
				<img height="150" src="<?php echo $this->url('vcard/photo', array('id' => $account->properties[$propertyId])) ?>"/>
	
	<?php else : ?>
				<input class="form-control" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" value="<?php echo $account->properties[$propertyId] ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />

	<?php endif;?>
			</div>
			<div class="col-sm-12"><p class="help-block" id="<?php echo (($property['type'] == 'date' || $property['type'] == 'number') ? 'input_' : '').$propertyId ?>_error"></p></div>
		</div>

<?php endforeach;?>

		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input name="submit" type="submit" id="submit-button" class="btn btn-success" value="<?php echo $this->translate('Register', 'ppit-commitment', $context->getLocale()) ?>">
				</div>
			</div>
		
		</form>
	</div>
</div>
