<h4 style="text-align: center"><strong><?php echo $context->getConfig('commitmentAccount/detail'.(($type) ? '/'.$type : ''))['title'][$context->getLocale()] ?></strong></h4>

<?php if ($account->id) : ?>
		<button type="button" class="btn btn-default action-btn" id="account-update-anchor" title="<?php echo $this->translate('Update', 'ppit-core', $context->getLocale()) ?>">
			<span class="glyphicon glyphicon-edit"></span>
		</button>

		<button type="button" class="btn btn-default action-btn" id="account-delete-anchor" title="<?php echo $this->translate('Delete', 'ppit-core', $context->getLocale()) ?>" <?php if (!$account->isDeletable()) echo 'disabled="disabled"' ?>>
			<span class="glyphicon glyphicon-trash"></span>
		</button>
<?php endif;?>

<!-- Form header -->
<?php echo $this->partial('/partials/form-header', array(
		'update_time' => $account->update_time,
		'message' => $message,
		'error' => $error,
		'csrfForm' => $csrfForm,
		'context' => $context,
));
?>
			
<!-- Global message -->
<?php if ($message == 'confirm-update') : ?>
<!--			<div class="form-group" id="message">
				<div class="col-sm-12"><h4><?php echo $this->translate('Are you sure you want to update the account?', 'ppit-commitment', $context->getLocale()) ?></h4></div>
			</div> -->
<?php elseif ($message == 'confirm-delete') : ?>
<!--				<div class="form-group" id="message">
						<div class="col-sm-12"><h4><?php echo $this->translate('Are you sure you want to delete the account?', 'ppit-commitment', $context->getLocale()) ?></h4></div>
					</div> -->
<?php endif;?>

<?php if (!$account->id) : ?>
		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input name="submit" type="submit" id="up-submit-button" class="btn btn-warning" value="<?php echo $this->translate('Add', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>

<?php elseif ($action == 'update') : ?>
		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input name="submit" type="submit" id="up-submit-button" class="btn btn-warning" value="<?php echo $this->translate('Update', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>

<?php elseif ($action == 'delete') : ?>
		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input name="submit" type="submit" id="up-submit-button" class="btn btn-danger" value="<?php echo $this->translate('Delete', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>
<?php endif;?>

<?php 
if ($account->id && $action != 'update' || $message == 'OK') $isDisabled = true; else $isDisabled = false;
?>

<?php foreach ($context->getConfig('commitmentAccount/update'.(($type) ? '/'.$type : '')) as $propertyId => $options) : ?>
	<?php 
	$property = $context->getConfig('commitmentAccount'.(($type) ? '/'.$type : ''))['properties'][$propertyId];
	if ($property['type'] == 'specific') $property = $context->getConfig($property['definition']);
	?>
		<div class="form-group" id="<?php echo (($property['type'] == 'date' || $property['type'] == 'number') ? 'input_' : '').$propertyId ?>_group">
			<label class="col-sm-5 control-label"><?php if ($options['mandatory']) echo '* ' ?><?php echo $property['labels'][$context->getLocale()] ?></label>
			<div class="col-sm-7">

	<?php if ($propertyId == 'n_first') : ?>
				<input class="form-control" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" value="<?php echo $account->contact_1->n_first ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
			
	<?php elseif ($propertyId == 'n_last') : ?>
				<input class="form-control" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" value="<?php echo $account->contact_1->n_last ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
			
	<?php elseif ($propertyId == 'email') : ?>
				<input class="form-control" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" value="<?php echo $account->contact_1->email ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />

	<?php elseif ($propertyId == 'closing_date') : ?>
				<input type="hidden" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" />
				<input class="form-control" id="input_<?php echo $propertyId ?>" name="input_<?php echo $propertyId ?>" value="<?php echo $context->decodeDate($account->closing_date) ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
				
	<?php elseif ($property['type'] == 'date') : ?>
				<input type="hidden" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" />
				<input class="form-control" id="input_<?php echo $propertyId ?>" name="input_<?php echo $propertyId ?>" value="<?php echo $context->decodeDate($account->properties[$propertyId]) ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />

	<?php elseif ($property['type'] == 'number') : ?>
				<input type="hidden" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" />
				<input class="form-control" id="input_<?php echo $propertyId ?>" name="input_<?php echo $propertyId ?>" value="<?php echo $context->formatFloat($account->properties[$propertyId], 2) ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />

	<?php elseif ($property['type'] == 'textarea') : ?>
				<textarea class="form-control" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?> <?php if ($isDisabled) echo 'disabled="disabled"'?>>
					<?php echo $account->properties[$propertyId] ?>
				</textarea>>

	<?php elseif ($property['type'] == 'select') : ?>
				<select class="form-control" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?>>
	    			<option />
		<?php foreach ($property['modalities'] as $key => $labels) : ?>
	    			<option value="<?php echo $key ?>" <?php if ($account->properties[$propertyId] == $key) echo 'selected="selected"' ?>><?php echo $labels[$context->getLocale()] ?></option>
		<?php endforeach;?>
				</select>

	<?php elseif ($property['type'] == 'photo') : ?>

<!-- Photo -->
				<img height="150" src="<?php echo $this->url('vcard/photo', array('id' => ($account->properties[$propertyId]) ? $account->properties[$propertyId] :  $account->contact_1->id)) ?>"/>
	
	<?php else : ?>
				<input class="form-control" id="<?php echo $propertyId ?>" value="<?php echo $account->properties[$propertyId] ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />

	<?php endif;?>
			</div>
			<div class="col-sm-12"><p class="help-block" id="<?php echo (($property['type'] == 'date' || $property['type'] == 'number') ? 'input_' : '').$propertyId ?>_error"></p></div>
		</div>

	<?php if ($property['type'] == 'photo' && !$isDisabled) : ?>
	    <div class="photo-group">
			<label class="col-sm-5 control-label"></label>
			<div class="col-sm-7">
				<input type="file" id="<?php echo $propertyId ?>" class="form-control" />
			</div>
		</div>
		<div>&nbsp;</div>
	<?php endif; ?>

<?php endforeach;?>

<?php if (!$account->id) : ?>

		<h4><?php echo $this->translate('User account creation', 'ppit-user', $context->getLocale())?></h4>

<!-- Connexion identifier -->		
		<div class="form-group" id="username_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Identifier', 'ppit-user', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input class="form-control" id="username" value="<?php echo $account->username ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
			</div>
			<div class="col-sm-12"><p class="help-block" id="username_error"><?php if ($error == 'Duplicate user') echo $this->translate('This identifier has already been chosen, please select another one', 'ppit-user', $context->getLocale()) ?></div>
		</div>

<!-- Accept notifications ? -->
		<div class="form-group" id="is_notified_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Accept notifications ?', 'ppit-user', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input type="checkbox" id="is_notified" class="form-control" value="1"<?php if ($account->is_notified) echo ' checked="checked"' ?><?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
			</div>
		</div>
					
<!-- Password -->
		<div class="form-group" id="new_password_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('New password', 'ppit-user', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input type="password" id="new_password" class="form-control" <?php if ($isDisabled) echo 'disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="new_password_error"></p></div>
		</div>

<!-- Password (2nd) -->
		<div class="form-group" id="new_password2_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('New password', 'ppit-user', $context->getLocale()) ?> (2)</label>
			<div class="col-sm-7">
				<input type="password" id="new_password2" class="form-control" <?php if ($isDisabled) echo 'disabled ="disabled"' ?>>
			</div>
			<div class="col-sm-12"><p class="help-block" id="new_password2_error"></p></div>
		</div>
		
<!-- Locale -->
		<div class="form-group" id="locale_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Locale', 'ppit-user', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<select name="locale" id="locale" class="form-control"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
					<option />
					<option value="en_US" <?php if ($account->locale == 'en_US') echo 'selected="selected"'; ?>>en_US</option>
					<option value="fr_FR" <?php if ($account->locale == 'fr_FR') echo 'selected="selected"'; ?>>fr_FR</option>
				</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="locale_error"></p></div>
		</div>

		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input name="submit" type="submit" id="submit-button" class="btn btn-warning" value="<?php echo $this->translate('Add', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>

<?php elseif ($action == 'update') : ?>
		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input name="submit" type="submit" id="submit-button" class="btn btn-warning" value="<?php echo $this->translate('Update', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>

<?php elseif ($action == 'delete') : ?>
		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input name="submit" type="submit" id="submit-button" class="btn btn-danger" value="<?php echo $this->translate('Delete', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>
<?php endif;?>
		
		</form>
