<style>
table.structured-data {
	font-size: 0.83em;
	border-width:1px; 
 	border-style:solid; 
	border-color:gray;
}
table.structured-data caption { 
	font-size:1.5em; 
	padding:1em 0 0.5em 1em;
}
table.structured-data th {
	color: #666;
//    font-size:0.83em;
	text-align: center;
	border-width:1px; 
 	border-style:solid; 
	border-color:gray;
	background-color:#DDD;
}

table.structured-data td {
	color: #666;
//	font-size: 0.83em;
	border-width:1px; 
 	border-style:solid; 
	border-color:gray;
}

table.structured-data td.subject {
	font-weight: bold;
}

table.structured-data tr.period {
	background-color:#DDD;
}
</style>
<h4 style="text-align: center">
	<strong><?php echo $context->getConfig('commitmentAccount/detail'.(($type) ? '/'.$type : ''))['title'][$context->getLocale()] ?></strong>
	<?php if ($account->id && $context->isDemoModeActive()) : ?>
		<a class="tip" href="#" title="<?php echo $context->getConfig('demo')['commitmentAccount/update'.(($type) ? '/'.$type : '')][$context->getLocale()] ?>">
		    <img src="<?php echo $this->basePath('img/tip.png') ?>" width="20" />
		</a>
	<?php endif;?>
</h4>

<?php if ($account->id) : ?>
		<button type="button" class="btn btn-default action-btn" id="account-update-anchor" title="<?php echo $this->translate('Update', 'ppit-core', $context->getLocale()) ?>">
			<span class="glyphicon glyphicon-edit"></span>
		</button>

		<button type="button" class="btn btn-default action-btn" id="account-delete-anchor" title="<?php echo $this->translate('Delete', 'ppit-core', $context->getLocale()) ?>" <?php if (!$account->isDeletable()) echo 'disabled="disabled"' ?>>
			<span class="glyphicon glyphicon-trash"></span>
		</button>

		<a href="<?php echo $this->url('commitmentAccount/indexCard', array('id' => $account->id, 'type' => $type)) ?>" target="_blank" title="<?php echo $this->translate('Print the index card', 'ppit-commitment', $context->getLocale()) ?>">
			<span class="glyphicon glyphicon-print"></span>
		</a>
<?php endif;?>

<!-- Form header -->
<?php echo $this->partial('/partials/form-header', array(
		'update_time' => $account->update_time,
		'message' => $message,
		'error' => $error,
		'csrfForm' => $csrfForm,
		'context' => $context,
));
?>
			
<!-- Global message -->
<?php if ($message == 'confirm-update') : ?>
<!--			<div class="form-group" id="message">
				<div class="col-sm-12"><h4><?php echo $this->translate('Are you sure you want to update the account?', 'ppit-commitment', $context->getLocale()) ?></h4></div>
			</div> -->
<?php elseif ($message == 'confirm-delete') : ?>
<!--				<div class="form-group" id="message">
						<div class="col-sm-12"><h4><?php echo $this->translate('Are you sure you want to delete the account?', 'ppit-commitment', $context->getLocale()) ?></h4></div>
					</div> -->
<?php endif;?>

<?php if (!$account->id) : ?>
		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input name="submit" type="submit" id="up-submit-button" class="btn btn-warning" value="<?php echo $this->translate('Add', 'ppit-core', $context->getLocale()) ?>">
<?php if ($context->isDemoModeActive()) : ?>
					<a class="tip" href="#" title="<?php echo $context->getConfig('demo')['commitmentAccount/add'.(($type) ? '/'.$type : '')][$context->getLocale()] ?>">
					    <img src="<?php echo $this->basePath('img/tip.png') ?>" width="20" />
					</a>
<?php endif;?>
				</div>
			</div>

<?php elseif ($action == 'update') : ?>
		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input name="submit" type="submit" id="up-submit-button" class="btn btn-warning" value="<?php echo $this->translate('Update', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>

<?php elseif ($action == 'delete') : ?>
		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input name="submit" type="submit" id="up-submit-button" class="btn btn-danger" value="<?php echo $this->translate('Delete', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>
<?php endif;?>

<?php 
if ($account->id && $action != 'update' || $message == 'OK') $isDisabled = true; else $isDisabled = false;
?>

<?php foreach ($context->getConfig('commitmentAccount/update'.(($type) ? '/'.$type : '')) as $propertyId => $options) : ?>
	<?php 
	$property = $context->getConfig('commitmentAccount'.(($type) ? '/'.$type : ''))['properties'][$propertyId];
	if ($property['type'] == 'repository') $property = $context->getConfig($property['definition']);
	?>
	<?php if ($property['type'] == 'title') : ?>
		<hr>
		<h5 style="text-align: center"><?php echo $property['labels'][$context->getLocale()] ?></h5>
		<div>&nbsp;</div>
	<?php else : ?>
	  <?php if (!array_key_exists('readonly', $options) || !$options['readonly'] || $account->properties[$propertyId]) : ?>
		<div class="form-group" id="<?php echo (($property['type'] == 'date' || $property['type'] == 'number') ? 'input_' : '').$propertyId ?>_group">
			<label class="col-sm-5 control-label"><?php if (array_key_exists('mandatory', $options) && $options['mandatory']) echo '* ' ?><?php echo $property['labels'][$context->getLocale()] ?></label>
			<div class="col-sm-7">

		<?php if ($propertyId == 'name') : ?>
				<input class="form-control" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" value="<?php echo $account->name ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />

		<?php elseif ($propertyId == 'n_first') : ?>
				<input class="form-control" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" value="<?php echo $account->contact_1->n_first ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
			
		<?php elseif ($propertyId == 'n_last') : ?>
				<input class="form-control" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" value="<?php echo $account->contact_1->n_last ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
			
		<?php elseif ($propertyId == 'email') : ?>
				<input class="form-control" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" value="<?php echo $account->contact_1->email ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
			
		<?php elseif ($propertyId == 'tel_work') : ?>
				<input class="form-control" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" value="<?php echo $account->contact_1->tel_work ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
			
		<?php elseif ($propertyId == 'tel_cell') : ?>
				<input class="form-control" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" value="<?php echo $account->contact_1->tel_cell ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
			
		<?php elseif ($propertyId == 'birth_date') : ?>
				<input type="hidden" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" />
				<input class="form-control" id="input_<?php echo $propertyId ?>" name="input_<?php echo $propertyId ?>" value="<?php echo $context->decodeDate($account->contact_1->birth_date) ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />

		<?php elseif ($propertyId == 'place_id') : ?>
				<select class="form-control" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?>>
	    			<option />
			<?php foreach ($places as $place) : ?>
	    			<option value="<?php echo $place->id ?>" <?php if ($account->properties[$propertyId] == $place->id) echo 'selected="selected"' ?>><?php echo $place->caption ?></option>
			<?php endforeach;?>
				</select>

		<?php elseif ($property['type'] == 'input') : ?>
				<input class="form-control" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" value="<?php echo $account->properties[$propertyId] ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />

		<?php elseif ($propertyId == 'closing_date') : ?>
				<input type="hidden" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" />
				<input class="form-control" id="input_<?php echo $propertyId ?>" name="input_<?php echo $propertyId ?>" value="<?php echo $context->decodeDate($account->closing_date) ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
				
		<?php elseif ($property['type'] == 'date') : ?>
				<input type="hidden" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" />
				<input class="form-control" id="input_<?php echo $propertyId ?>" name="input_<?php echo $propertyId ?>" value="<?php echo $context->decodeDate($account->properties[$propertyId]) ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />

		<?php elseif ($property['type'] == 'number') : ?>
				<input type="hidden" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" />
				<input class="form-control" id="input_<?php echo $propertyId ?>" name="input_<?php echo $propertyId ?>" value="<?php echo $context->formatFloat($account->properties[$propertyId], 2) ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />

		<?php elseif ($property['type'] == 'textarea') : ?>
				<textarea class="form-control" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?>><?php echo $account->properties[$propertyId] ?></textarea>

		<?php elseif ($property['type'] == 'log') : ?>
				<textarea class="form-control" id="<?php echo $propertyId ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?>></textarea>

		<?php elseif ($property['type'] == 'select') : ?>
				<select class="form-control" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?>>
	    			<option />
			<?php foreach ($property['modalities'] as $key => $labels) : ?>
	    			<option value="<?php echo $key ?>" <?php if ($account->properties[$propertyId] == $key) echo 'selected="selected"' ?>><?php echo $labels[$context->getLocale()] ?></option>
			<?php endforeach;?>
				</select>

		<?php elseif ($property['type'] == 'photo') : ?>

<!-- Photo -->
				<img height="150" src="<?php echo $this->basePath('photos/'.$account->properties[$propertyId]) ?>.jpg"/>

<!-- Structured data -->

		<?php elseif ($property['type'] == 'structured') : ?>
			<?php foreach ($account->properties[$propertyId] as $itemId => $item) : ?>
				<?php if (is_array($item)) : ?>
				<table class="table structured-data">
					<?php reset($item); ?>
					<tr>
						<?php foreach (current($item) as $cellId => $cell) : ?>
						<th><?php echo $cellId ?></th>
						<?php endforeach;?>
					</tr>
					<?php foreach ($item as $row) : ?>
					<tr>
						<?php foreach ($row as $cellId => $cell) : ?>
						<td><?php echo $cell ?></td>
						<?php endforeach;?>
					</tr>
					<?php endforeach;?>
				</table>
				<?php else : ?>
				<div>&nbsp;</div>
				<table class="table structured-data">
					<tr><th><?php echo $itemId ?></th></tr>
					<tr><td><?php echo $item ?></td></tr>
				</table>
				<?php endif;?>
			<?php endforeach;?>
	
		<?php else : ?>
				<input class="form-control" id="<?php echo $propertyId ?>" value="<?php echo $account->properties[$propertyId] ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />

		<?php endif;?>
			</div>
			<div class="col-sm-12"><p class="help-block" id="<?php echo (($property['type'] == 'date' || $property['type'] == 'number') ? 'input_' : '').$propertyId ?>_error"></p></div>
		</div>

		<?php if ($property['type'] == 'photo' && !$isDisabled) : ?>
	    <div class="photo-group">
			<label class="col-sm-5 control-label"></label>
			<div class="col-sm-7">
				<input type="file" id="<?php echo $propertyId ?>" class="form-control" />
			</div>
		</div>
		<div>&nbsp;</div>

		<?php elseif ($property['type'] == 'log' && $account->properties[$propertyId]) : ?>
<!-- Display the history -->
		<div id="<?php echo $propertyId ?>-history-panel" class="panel panel-default">
			<div class="panel-body">
			<?php foreach ($account->properties[$propertyId] as $comment) : ?>
				<div class="row">
					<div class="col-md-12">
						<strong><?php echo $context->decodeDate(substr($comment['time'], 0, 10)).substr($comment['time'], 10) ?>:</strong>&nbsp;
						<?php if (array_key_exists('status', $comment)) echo $context->getconfig('commitmentAccount'.(($type) ? '/'.$type : ''))['statuses'][$comment['status']]['labels'][$context->getLocale()] ?>&nbsp;
						(<?php echo $comment['n_fn'] ?>)
					</div>
				</div>
				<div class="row">
					<div class="col-md-2" align="right">&nbsp;</div>
					<div class="col-md-10"><em><?php echo $comment['comment'] ?></em></div>
				</div>
			<?php endforeach;?>
			</div>
		</div>
		<div>&nbsp;</div>
		<div>
		<?php endif; ?>
	  <?php endif;?>
	<?php endif;?>

<?php endforeach;?>

<?php if (!$account->id) : ?>
		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input name="submit" type="submit" id="submit-button" class="btn btn-warning" value="<?php echo $this->translate('Add', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>

<?php elseif ($action == 'update') : ?>
		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input name="submit" type="submit" id="submit-button" class="btn btn-warning" value="<?php echo $this->translate('Update', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>

<?php elseif ($action == 'delete') : ?>
		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input name="submit" type="submit" id="submit-button" class="btn btn-danger" value="<?php echo $this->translate('Delete', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>
<?php endif;?>
		
		</form>
