<div class="panel panel-default">
	<div class="panel-heading" style="background:  <?php echo $context->getConfig('styleSheet')['panelHeadingBackground'] ?>; color: <?php echo $context->getConfig('styleSheet')['panelHeadingColor'] ?>">
		<strong><?php echo $this->translate('Add a photograph', 'ppit-commitment', $context->getLocale()) ?></strong>
 		<div class="btn-group pull-right">
			<button type="button" class="btn btn-default" title="<?php echo $this->translate('Return to list', 'ppit-core', $context->getLocale()) ?>" id="remove-anchor">
				<span class="glyphicon glyphicon-remove"></span>
			</button>
 		 </div>
	</div>
	<div class="panel-body">

<!-- Global message -->
<?php if ($message == 'OK') : ?>
		<div id="message">
			<div class="alert alert-success"><h4><?php echo $this->translate('Your request have been registered', 'ppit-core', $context->getLocale()) ?></h4></div>
		</div>
<?php endif;?>

<!-- Consistency error -->
<?php if ($error == 'Consistency') : ?>
		<div class="form-group">
			<div class="alert alert-danger"><p class="help-block"><?php echo $this->translate('An error has occurred. Please check your internet access', 'ppit-core', $context->getLocale()) ?></p></div>
		</div>
<?php endif;?>

<!--  CSRF -->
<?php $element = $csrfForm->get('csrf') ?>
		<div class="form-group">
			<?php echo $this->formElement($element) ?>
<?php if ($this->formElementErrors($element)) : ?>
			<div class="alert alert-danger"><p class="help-block"><?php echo $this->translate('The form has expired, please input again', 'ppit-core', $context->getLocale()) ?></p></div>
<?php endif;?>
		</div>

<?php if ($message == 'OK') $isDisabled = true; else $isDisabled = false; ?>

		<div class="form-group" id="folder_group">
			<label class="col-sm-4 control-label">* <?php echo $this->translate('Folder', 'ppit-document', $context->getLocale()) ?></label>
			<div class="col-sm-8">
				<select class="form-control" id="folder" <?php if ($isDisabled) echo 'disabled="disabled"'?>>
	    			<option />
		<?php foreach ($context->getConfig('ppitDocument')['dropbox']['folders'] as $key => $value) : ?>
	    			<option value="<?php echo $key ?>" <?php if ($folder == $value) echo 'selected="selected"' ?>><?php echo $value ?></option>
		<?php endforeach;?>
				</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="folder_error"></p></div>
		</div>
	    
<!-- document -->
		<div class="form-group" id="attachment_group">
			<label class="col-sm-4 control-label">* <?php echo $this->translate('Document', 'ppit-socument', $context->getLocale())?></label>
			<div class="col-sm-8">
				<input type="file" id="attachment" class="form-control" <?php if ($isDisabled) echo 'disabled="disabled"'?> />
			</div>
		</div>

		<div>&nbsp;</div>		

		<div class="form-group">
			<div class="col-sm-4">&nbsp;</div>
			<div class="col-sm-8">
				<input name="submit" type="submit" id="submit-button" class="btn btn-warning" value="<?php echo $this->translate('Add', 'ppit-core', $context->getLocale()) ?>">
			</div>
		</div>
	</div>
</div>
