<div class="panel panel-default">
	<div class="panel-heading" style="background: <?php echo $context->getConfig('styleSheet')['panelHeadingBackground'] ?>; color: <?php echo $context->getConfig('styleSheet')['panelHeadingColor'] ?>">
		<?php echo $this->translate('Importer un fichier', 'ppit-commitment', $context->getLocale()) ?>
 		<div class="btn-group pull-right">
			<button type="button" class="btn btn-default" title="<?php echo $this->translate('Close', 'ppit-core', $context->getLocale()) ?>" id="<?php echo 'remove-anchor' ?>">
				<span class="glyphicon glyphicon-remove"></span>
			</button>
		</div>
	</div>
    <div class="panel-body">

		<!-- Form header -->
		<?php echo $this->partial('/partials/form-header', array(
					'update_time' => null,
					'message' => $message,
					'error' => $error,
					'csrfForm' => $csrfForm,
					'context' => $context,
		)) ?>

		<?php if ($message == 'OK') $isDisabled = true; else $isDisabled = false; ?>
	
		<!-- Type -->
		<div class="form-group" id="type_group">
			<label class="col-sm-5 control-label">* <?php echo $this->translate('Type', 'ppit-core', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<select name="type" id="type" class="form-control"<?php if (isset($isDisabled) && $isDisabled) echo ' disabled ="disabled"' ?>>
					<option value=""><-- <?php echo $this->translate('Please choose', 'ppit-core', $context->getLocale()) ?> --></option>
<?php foreach ($context->getConfig('commitmentMessage')['importTypes'] as $type => $description) : ?>
					<option value="<?php echo $type ?>" <?php if ($commitmentMessage->type == $type) echo 'selected="selected"'; ?>><?php echo $description[$context->getLocale()] ?></option>
<?php endforeach;?>
				</select>
			</div>
			<div class="col-sm-12"><p class="help-block" id="type_error"></p></div>
		</div>

		<!-- Order form -->
	    <div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Fichier', 'ppit-commitment', $context->getLocale())?></label>
			<div class="col-sm-7">
				<input type="file" name="order-form" id="order-form" class="form-control" />
			</div>
		</div>

<?php if ($message == 'OK') : ?>

<!-- Foot return link -->
		<div class="form-group" id="foot_return_link">
			<div class="col-sm-5">&nbsp;</div>
			<div class="col-sm-7">
				<button type="button" class="btn btn-default" title="<?php echo $this->translate('Close', 'ppit-core', $context->getLocale()) ?>" id="<?php echo 'return-anchor' ?>">
					<span><?php echo $this->translate('Return', 'ppit-core', $context->getLocale()) ?></span>
				</button>
			</div>
		</div>

<?php else : ?>

<!-- Submit button -->
	    <div class="form-group">
			<div class="col-sm-5">&nbsp;</div>
			<div class="col-sm-7">
				<input name="submit" type="submit" id="update-submit-button" class="btn btn-warning" value="<?php echo $this->translate('Confirm', 'ppit-core', $context->getLocale()) ?>">
				&nbsp;&nbsp;
				<button type="button" class="btn btn-default" title="<?php echo $this->translate('Cancel', 'ppit-core', $context->getLocale()) ?>" id="<?php echo 'cancel-anchor' ?>">
					<span><?php echo $this->translate('Cancel', 'ppit-core', $context->getLocale()) ?></span>
				</button>
			</div>
		</div>

<?php endif;?>

	</div>
</div>
