<div class="panel panel-default">
	<div class="panel-heading">
		<?php echo $this->translate('Re-submit an XML message', 'ppit-commitment', $context->getLocale()) ?>
 		<div class="btn-group pull-right">
			<button type="button" class="btn btn-default" title="<?php echo $this->translate('Close', 'ppit-core', $context->getLocale()) ?>" id="<?php echo 'remove-anchor' ?>">
				<span class="glyphicon glyphicon-remove"></span>
			</button>
 		</div>
	</div>
    <div class="panel-body">

		<!-- Form header -->
		<?php echo $this->partial('/partials/form-header', array(
					'update_time' => $xmlMessage->update_time,
					'message' => $message,
					'error' => $error,
					'csrfForm' => $csrfForm,
					'context' => $context,
		)) ?>

		<?php if ($message == 'OK') $isDisabled = true; else $isDisabled = false; ?>

<?php if ($message == 'OK') : ?>

<!-- Foot return link -->
		<div class="form-group" id="foot_return_link">
			<div class="col-sm-5">&nbsp;</div>
			<div class="col-sm-7">
				<button type="button" class="btn btn-default" title="<?php echo $this->translate('Close', 'ppit-core', $context->getLocale()) ?>" id="<?php echo 'return-anchor' ?>">
					<span><?php echo $this->translate('Return', 'ppit-core', $context->getLocale()) ?></span>
				</button>
			</div>
		</div>

<?php else : ?>

<!-- Submit button -->
	    <div class="form-group">
			<div class="col-sm-5">&nbsp;</div>
			<div class="col-sm-7">
				<input name="submit" type="submit" id="update-submit-button" class="btn btn-warning" value="<?php echo $this->translate('Confirm', 'ppit-core', $context->getLocale()) ?>">
				&nbsp;&nbsp;
				<button type="button" class="btn btn-default" title="<?php echo $this->translate('Cancel', 'ppit-core', $context->getLocale()) ?>" id="<?php echo 'cancel-anchor' ?>">
					<span><?php echo $this->translate('Cancel', 'ppit-core', $context->getLocale()) ?></span>
				</button>
			</div>
		</div>

<?php endif;?>

	</div>
</div>
