<!-- 
/**
 * PpitCore V1.0 (https://github.com/p-pit/PpitCore)
 *
 * @link      https://github.com/p-pit/PpitCore
 * @copyright Copyright (c) 2016 Bruno Lartillot
 * @license   https://github.com/p-pit/PpitCore/blob/master/license.txt GNU-GPL license
 */
-->

<h4 style="text-align: center">
	<strong><?php echo $this->translate('Send a debit order', 'ppit-commitment', $context->getLocale()) ?></strong>
</h4>

<!-- Form header -->
<form action="" id="ppit-form" method="post" class="form-horizontal" enctype="multipart/form-data">
			
<!-- Global message -->
<?php if ($message == 'OK') : ?>
	<div id="message">
			<div class="alert alert-success"><h4><?php echo $this->translate('Your request has been registered', 'ppit-core', $context->getLocale()) ?></h4></div>
	</div>
<?php endif;?>

<?php 
if ($message == 'OK') $isDisabled = true; else $isDisabled = false;
?>
	<div class="panel-body">

<?php if ($message != 'OK') : ?>
 
	<div class="form-group">
		<label class="col-sm-5 control-label">* <?php echo $this->translate('Place to credit', 'ppit-commitment', $context->getLocale()) ?></label>
		<div class="col-sm-7">
			<select class="form-control" id="place_id" <?php if ($isDisabled) echo 'disabled' ?>>
	<?php foreach ($places as $place_id => $place) : ?>
				<option value="<?php echo $place_id?>"><?php echo $place['caption'] ?></option>
	<?php endforeach;?>
			</select>
		</div>
	</div>
    <div class="form-group">
		<div class="col-sm-5"><?php echo $this->translate('Password', 'ppit-core', $context->getLocale()) ?></div>
		<div class="col-sm-7">
			<input type="password" class="form-control" id="term-passphrase">
		</div>
	</div>
    <div class="form-group">
		<div class="col-sm-5">&nbsp;</div>
		<div class="col-sm-7">
			<input id="term-control-button" class="btn btn-warning" value="<?php echo $this->translate('Control file', 'ppit-commitment', $context->getLocale()) ?>">
		</div>
	</div>
    <div class="form-group">
		<div class="col-sm-5">&nbsp;</div>
		<div class="col-sm-7">
			<input id="term-debit-button" class="btn btn-danger" value="<?php echo $this->translate('Bank file', 'ppit-commitment', $context->getLocale()) ?>">
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-12">
			<div class="alert alert-warning" id="term-debit-alert" style="text-align: center">
				<strong><?php echo $this->translate('Please confirm', 'ppit-core', $context->getLocale()) ?></strong>
			</div>
		</div>
	</div>
<?php endif;?>
	</div>
</form>
