<!-- 
/**
 * PpitCore V1.0 (https://github.com/p-pit/PpitCore)
 *
 * @link      https://github.com/p-pit/PpitCore
 * @copyright Copyright (c) 2016 Bruno Lartillot
 * @license   https://github.com/p-pit/PpitCore/blob/master/license.txt GNU-GPL license
 */
-->

<h4 style="text-align: center">
	<strong><?php echo $this->translate('Send a debit order', 'ppit-commitment', $context->getLocale()) ?></strong>
</h4>

<!-- Form header -->
<form action="" id="ppit-form" method="post" class="form-horizontal" enctype="multipart/form-data">
			
<!-- Global message -->
<?php if ($message == 'OK') : ?>
	<div id="message">
			<div class="alert alert-success"><h4><?php echo $this->translate('Your request has been registered', 'ppit-core', $context->getLocale()) ?></h4></div>
	</div>
<?php endif;?>

<?php 
if ($message == 'OK') $isDisabled = true; else $isDisabled = false;
?>
	<div class="panel-body">

<?php if ($message != 'OK') : ?>
    <div class="form-group">
		<div class="col-sm-5">&nbsp;</div>
		<div class="col-sm-7">
			<input id="term-debit-button" class="btn btn-default" value="<?php echo $this->translate('Send', 'ppit-core', $context->getLocale()) ?>">
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-12">
			<div class="alert alert-warning" id="term-debit-alert" style="text-align: center">
				<strong><?php echo $this->translate('Please confirm', 'ppit-core', $context->getLocale()) ?></strong>
			</div>
		</div>
	</div>
<?php endif;?>
	</div>
</form>
