<!-- Form header -->
<?php echo $this->partial('/partials/form-header', array(
		'formId' => 'generate-term-form',
 		'update_time' => $term->update_time,
		'message' => $message,
		'error' => $error,
		'csrfForm' => $csrfForm,
		'context' => $context,
));
?>
		<div class="form-group">
			<div class="col-sm-5">&nbsp;</div>
			<div class="col-sm-7">
				<input name="submit" type="submit" id="up-submit-button" class="btn btn-warning" value="<?php echo $this->translate('Add', 'ppit-core', $context->getLocale()) ?>">
			</div>
		</div>

		<div class="form-group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Commitment', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input class="form-control" value="<?php echo $term->commitment_caption ?>" disabled="disabled" />
			</div>
		</div>

		<div class="form-group" id="number_of_terms-group">
			<label class="col-sm-5 control-label">* <?php echo $this->translate('Number of terms', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input class="form-control" id="number_of_terms" />
			</div>
			<div class="col-sm-12"><p class="help-block" id="number_of_terms-error"></p></div>
		</div>

		<div class="form-group" id="input_first_term_date-group">
			<label class="col-sm-5 control-label">* <?php echo $this->translate('First term date', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input type="hidden" id="first_term_date" />
				<input class="form-control" id="input_first_term_date" />
			</div>
			<div class="col-sm-12"><p class="help-block" id="input_first_term_date-error"></p></div>
		</div>

		<div class="form-group" id="periodicity-group">
			<label class="col-sm-5 control-label">* <?php echo $this->translate('Days between two terms', 'ppit-commitment', $context->getLocale()) ?></label>
			<div class="col-sm-7">
				<input class="form-control" id="periodicity" />
			</div>
			<div class="col-sm-12"><p class="help-block" id="periodicity-error"></p></div>
		</div>

<?php $meansOfPayment = $context->getConfig('commitmentTerm')['properties']['means_of_payment'] ?>
		<div class="form-group">
			<label class="col-sm-5 control-label">* <?php echo $context->localize($meansOfPayment['labels']) ?></label>
			<div class="col-sm-7">
				<select class="form-control" id="means_of_payment">
					<option />
<?php foreach ($meansOfPayment['modalities'] as $modalityId => $modality) : ?>
					<option value="<?php echo $modalityId ?>"><?php echo $context->localize($modality) ?>
<?php endforeach;?>
				</select>
			</div>
		</div>

		<div class="form-group">
			<div class="col-sm-5">&nbsp;</div>
			<div class="col-sm-7">
				<input name="submit" type="submit" id="submit-button" class="btn btn-warning" value="<?php echo $this->translate('Add', 'ppit-core', $context->getLocale()) ?>">
			</div>
		</div>
		
	</form>
