<div class="panel panel-default">
	<div class="panel-heading" style="background: <?php echo $context->getConfig('styleSheet')['panelHeadingBackground'] ?>; color: <?php echo $context->getConfig('styleSheet')['panelHeadingColor'] ?>">
		<strong>
			<?php 
			$title = (isset ($context->getConfig('commitmentTerm/search')['title']) ? $context->getConfig('commitmentTerm/search')['title'][$context->getLocale()] : $this->translate('Terms', 'ppit-commitment', $context->getLocale()));
			echo $title;
			?>
			(<span id="mode-text"></span>)
		</strong>
		
<?php if ($context->isDemoModeActive()) : ?>
		<a class="tip" href="#" title="<?php echo $context->getConfig('demo')['commitmentTerm/search/title'][$context->getLocale()] ?>">
		    <img src="<?php echo $this->basePath('img/tip.png') ?>" width="20" />
		</a>
<?php endif;?>
	</div>
	<div class="panel-body">

		<div class="col-md-6">

<!-- Filters -->
		
<?php foreach ($searchPage['properties'] as $propertyId => $options) : ?>
	<?php $property = $termProperties[$propertyId]; ?>
	<?php $label = $property['labels'][$context->getLocale()] ?>

	<?php if (in_array($property['type'], array('date', 'time', 'datetime', 'number'))) : ?>

			<label class="col-sm-6 control-label"><?php echo $label ?></label>
			<div class="input-group search">
			    <span class="input-group-addon">
					<input type="checkbox" class="search_check" id="search_check_min_<?php echo $propertyId ?>">
				</span>
	    		<input class="form-control search_input" type="text" id="search_min_<?php echo $propertyId ?>" class="form-control" placeholder="<?php echo $this->translate('Min', 'ppit-core', $context->getLocale()) ?>" />
			</div>

			<label class="col-sm-6 control-label">&nbsp;</label>
			<div class="input-group search">
			    <span class="input-group-addon">
					<input type="checkbox" class="search_check" id="search_check_max_<?php echo $propertyId ?>">
				</span>
	    		<input class="form-control search_input" type="text" id="search_max_<?php echo $propertyId ?>" class="form-control" placeholder="<?php echo $this->translate('Max', 'ppit-core', $context->getLocale()) ?>" />
			</div>

	<?php elseif ($property['type'] == 'select') : ?>

		<?php
		$modalities = array();
		
		if ($propertyId == 'place_id') foreach ($places as $place) {
			$modalities[$place->id] = $place->caption;
		} 
		elseif ($property['type'] == 'select') {
			foreach ($property['modalities'] as $modalityId => $modality) {
				$modalities[$modalityId] = $modality[$context->getLocale()];
			}
		}
		else {
			foreach ($context->getConfig($property['name'])['modalities'] as $modalityId => $modality) {
				$modalities[$modalityId] = $modality[$context->getLocale()];
			}
		}
		?>
			<label class="col-sm-6 control-label"><?php echo $label ?></label>
			<div class="input-group search">
			    <span class="input-group-addon">
					<input type="checkbox" class="search_check" id="search_check_<?php echo $propertyId ?>">
				</span>
				<select id="search_<?php echo $propertyId ?>" class="selectpicker" <?php if (array_key_exists('multiple', $options) && $options['multiple']) echo 'multiple' ?>>
					<option value=""></option>
		<?php foreach ($modalities as $modalityId => $modalityLabel) : ?>
		    		<option value="<?php echo $modalityId ?>"><?php echo $modalityLabel ?></option>
		<?php endforeach;?>
		    	</select>
			</div>
	
	<?php else : ?>
			<label class="col-sm-6 control-label"><?php echo $label ?></label>
			<div class="input-group search">
			    <span class="input-group-addon">
					<input type="checkbox" class="search_check" id="search_check_<?php echo $propertyId ?>">
				</span>
				<input class="form-control search_input" type="text" id="search_<?php echo $propertyId ?>" placeholder="<?php echo $this->translate('Contains', 'ppit-core', $context->getLocale()) ?>" />
			</div>

	<?php endif;?>
<?php endforeach;?>

			<div class="col-sm-6">&nbsp;</div>
		
			<div class="col-sm-3">
	    		<button type="button" class="form-control btn btn-default btn-xs" title="<?php echo $this->translate('Search', 'ppit-core', $context->getLocale()) ?>" id="search-button">
					<span class="glyphicon glyphicon-search"></span>
				</button>
			</div>
			<div class="col-sm-3 search">
	    		<button type="button" class="form-control btn btn-default btn-xs" title="<?php echo $this->translate('Erase', 'ppit-core', $context->getLocale()) ?>" id="erase-button">
					<span class="glyphicon glyphicon-remove"></span>
				</button>
<?php if ($context->isDemoModeActive()) : ?>
				<a class="tip" href="#" title="<?php echo $context->getConfig('demo')['commitmentTerm/search/x'][$context->getLocale()] ?>">
				    <img src="<?php echo $this->basePath('img/tip.png') ?>" width="20" />
				</a>
<?php endif;?>
			</div>


<!-- Actions -->
	    <div>
	    		<button type="button" class="btn btn-default" title="<?php echo $this->translate('Export', 'ppit-core', $context->getLocale()) ?>" id="export-button">
					<span class="glyphicon glyphicon-cloud-download"></span>
					<span><?php echo $this->translate('Export', 'ppit-core', $context->getLocale())?></span>
				</button>
<?php if ($context->isDemoModeActive()) : ?>
				<a class="tip" href="#" title="<?php echo $context->getConfig('demo')['commitmentTerm/search/export'][$context->getLocale()] ?>">
				    <img src="<?php echo $this->basePath('img/tip.png') ?>" width="20" />
				</a>
<?php endif;?>
	    </div>
		</div>
	    
		<div>&nbsp;</div>

<!-- Add or update section -->
		<input type="hidden" id="limit" value="50" />
		<div id="term-list-panel"></div>
	</div>
</div>
