<h4 style="text-align: center"><strong><?php echo $context->getConfig('commitmentTerm/detail')['title'][$context->getLocale()] ?></strong></h4>

<?php if ($term->id) : ?>
		<button type="button" class="btn btn-default action-btn" id="term-update-anchor" title="<?php echo $this->translate('Update', 'ppit-core', $context->getLocale()) ?>">
			<span class="glyphicon glyphicon-edit"></span>
		</button>

		<button type="button" class="btn btn-default action-btn" id="term-delete-anchor" title="<?php echo $this->translate('Delete', 'ppit-core', $context->getLocale()) ?>" <?php if (!$term->isDeletable()) echo 'disabled="disabled"' ?>>
			<span class="glyphicon glyphicon-trash"></span>
		</button>
<?php endif;?>

<!-- Form header -->
<?php echo $this->partial('/partials/form-header', array(
		'update_time' => $term->update_time,
		'message' => $message,
		'error' => $error,
		'csrfForm' => $csrfForm,
		'context' => $context,
));
?>
			
<!-- Global message -->
<?php if ($message == 'confirm-update') : ?>
<!--			<div class="form-group" id="message">
				<div class="col-sm-12"><h4><?php echo $this->translate('Are you sure you want to update the term?', 'ppit-commitment', $context->getLocale()) ?></h4></div>
			</div> -->
<?php elseif ($message == 'confirm-delete') : ?>
<!--				<div class="form-group" id="message">
						<div class="col-sm-12"><h4><?php echo $this->translate('Are you sure you want to delete the term?', 'ppit-commitment', $context->getLocale()) ?></h4></div>
					</div> -->
<?php endif;?>

<?php if (!$term->id) : ?>
		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input name="submit" type="submit" id="up-submit-button" class="btn btn-warning" value="<?php echo $this->translate('Add', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>

<?php elseif ($action == 'update') : ?>
		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input name="submit" type="submit" id="up-submit-button" class="btn btn-warning" value="<?php echo $this->translate('Update', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>

<?php elseif ($action == 'delete') : ?>
		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input name="submit" type="submit" id="up-submit-button" class="btn btn-danger" value="<?php echo $this->translate('Delete', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>
<?php endif;?>

<?php 
if ($term->id && $action != 'update' || $message == 'OK') $isDisabled = true; else $isDisabled = false;
?>

<?php foreach ($context->getConfig('commitmentTerm/update') as $propertyId => $options) : ?>
	<?php 
	$property = $context->getConfig('commitmentTerm')['properties'][$propertyId];
	if ($property['type'] == 'repository') $property = $context->getConfig($property['definition']);
	?>
		<div class="form-group" id="<?php echo (($property['type'] == 'date' || $property['type'] == 'number') ? 'input_' : '').$propertyId ?>_group">
			<label class="col-sm-5 control-label"><?php if ($options['mandatory']) echo '* ' ?><?php echo $property['labels'][$context->getLocale()] ?></label>
			<div class="col-sm-7">
				
	<?php if ($property['type'] == 'date') : ?>
				<input type="hidden" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" />
				<input class="form-control" id="input_<?php echo $propertyId ?>" name="input_<?php echo $propertyId ?>" value="<?php echo $context->decodeDate($term->properties[$propertyId]) ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />

	<?php elseif ($property['type'] == 'number') : ?>
				<input type="hidden" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" />
				<input class="form-control" id="input_<?php echo $propertyId ?>" name="input_<?php echo $propertyId ?>" value="<?php echo $context->formatFloat($term->properties[$propertyId], 2) ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />

	<?php elseif ($property['type'] == 'textarea') : ?>
				<textarea class="form-control" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?> <?php if ($isDisabled) echo 'disabled="disabled"'?>>
					<?php echo $term->properties[$propertyId] ?>
				</textarea>>

	<?php elseif ($property['type'] == 'select') : ?>
				<select class="form-control" id="<?php echo $propertyId ?>" name="<?php echo $propertyId ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?>>
	    			<option />
		<?php foreach ($property['modalities'] as $key => $labels) : ?>
	    			<option value="<?php echo $key ?>" <?php if ($term->properties[$propertyId] == $key) echo 'selected="selected"' ?>><?php echo $labels[$context->getLocale()] ?></option>
		<?php endforeach;?>
				</select>
	
	<?php else : ?>
				<input class="form-control" id="<?php echo $propertyId ?>" value="<?php echo $term->properties[$propertyId] ?>" <?php if ($isDisabled) echo 'disabled="disabled"'?> />

	<?php endif;?>
			</div>
			<div class="col-sm-12"><p class="help-block" id="<?php echo (($property['type'] == 'date' || $property['type'] == 'number') ? 'input_' : '').$propertyId ?>_error"></p></div>
		</div>

<?php endforeach;?>

<?php if (!$term->id) : ?>
		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input name="submit" type="submit" id="submit-button" class="btn btn-warning" value="<?php echo $this->translate('Add', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>

<?php elseif ($action == 'update') : ?>
		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input name="submit" type="submit" id="submit-button" class="btn btn-warning" value="<?php echo $this->translate('Update', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>

<?php elseif ($action == 'delete') : ?>
		    <div class="form-group">
				<div class="col-sm-5">&nbsp;</div>
				<div class="col-sm-7">
					<input name="submit" type="submit" id="submit-button" class="btn btn-danger" value="<?php echo $this->translate('Delete', 'ppit-core', $context->getLocale()) ?>">
				</div>
			</div>
<?php endif;?>
		
		</form>
